#include "authority_core_v2.hpp"

#import <Foundation/Foundation.h>
#import <Security/Security.h>
#import <xpc/xpc.h>
#include <CommonCrypto/CommonHMAC.h>

#include <bsm/audit.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <cstring>
#include <map>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace kp=kristin::p1a;
namespace {
NSData* data(std::string_view s){return [NSData dataWithBytes:s.data() length:s.size()];}
std::string base64(const unsigned char*p,std::size_t n){return [[[NSData alloc] initWithBytes:p length:n] base64EncodedStringWithOptions:0].UTF8String;}
std::string cf_error(CFErrorRef e){if(!e)return"unknown";CFStringRef d=CFErrorCopyDescription(e);if(!d)return"unknown";char b[1024]{};const Boolean converted=CFStringGetCString(d,b,static_cast<CFIndex>(sizeof(b)),kCFStringEncodingUTF8);CFRelease(d);return converted?std::string(b):std::string("unknown");}
std::vector<unsigned char> keychain_secret(NSString*service){NSDictionary*q=@{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:service,(__bridge id)kSecAttrAccount:@"com.kristin.p1.authority",(__bridge id)kSecReturnData:@YES,(__bridge id)kSecMatchLimit:(__bridge id)kSecMatchLimitOne};CFTypeRef result=nullptr;OSStatus st=SecItemCopyMatching((__bridge CFDictionaryRef)q,&result);if(st!=errSecSuccess||!result)throw std::runtime_error("keychain_secret_missing");NSData*d=(__bridge_transfer NSData*)result;return std::vector<unsigned char>((const unsigned char*)d.bytes,(const unsigned char*)d.bytes+d.length);}
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
void store_keychain_secret(NSString*service,NSData*secret,const std::filesystem::path&service_binary){SecTrustedApplicationRef trusted=nullptr;if(SecTrustedApplicationCreateFromPath(service_binary.c_str(),&trusted)!=errSecSuccess||!trusted)throw std::runtime_error("keychain_trusted_application_failed");const void*items[]={trusted};CFArrayRef apps=CFArrayCreate(kCFAllocatorDefault,items,1,&kCFTypeArrayCallBacks);SecAccessRef access=nullptr;OSStatus access_status=SecAccessCreate(CFSTR("Kristin P1 authority service-only secret"),apps,&access);CFRelease(apps);CFRelease(trusted);if(access_status!=errSecSuccess||!access)throw std::runtime_error("keychain_access_create_failed");NSDictionary*q=@{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:service,(__bridge id)kSecAttrAccount:@"com.kristin.p1.authority"};SecItemDelete((__bridge CFDictionaryRef)q);NSMutableDictionary*v=[q mutableCopy];v[(__bridge id)kSecValueData]=secret;v[(__bridge id)kSecAttrAccessible]=(__bridge id)kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;v[(__bridge id)kSecAttrAccess]=(__bridge id)access;OSStatus st=SecItemAdd((__bridge CFDictionaryRef)v,nullptr);CFRelease(access);if(st!=errSecSuccess)throw std::runtime_error("keychain_secret_store_failed");}
#pragma clang diagnostic pop

std::array<unsigned char,CC_SHA256_DIGEST_LENGTH> legacy_hmac_sha256(const std::vector<unsigned char>&key,std::string_view payload){std::array<unsigned char,CC_SHA256_DIGEST_LENGTH>out{};
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
CCHmac(kCCHmacAlgSHA256,key.data(),key.size(),payload.data(),payload.size(),out.data());
#pragma clang diagnostic pop
return out;}

struct config final{std::string mach_service,desktop_requirement,worker_requirement,service_instance;std::filesystem::path policy,state,audit,revocations,approvals,service_binary;std::string grant_service,owner_service,key_tag;};
config load_config(const std::filesystem::path&p){auto v=kp::json::parse(kp::read_text_file(p));const auto&o=v.as_object();config c;c.mach_service=kp::json::required_string(o,"machServiceName");c.desktop_requirement=kp::json::required_string(o,"desktopCodeRequirement");c.worker_requirement=kp::json::required_string(o,"workerCodeRequirement");c.service_instance=kp::json::required_string(o,"serviceInstanceId");c.policy=kp::json::required_string(o,"policySnapshotPath");c.state=kp::json::required_string(o,"statePath");c.audit=kp::json::required_string(o,"auditPath");c.revocations=kp::json::required_string(o,"revocationsPath");c.approvals=kp::json::required_string(o,"approvalsPath");c.grant_service=kp::json::required_string(o,"grantKeychainService");c.owner_service=kp::json::required_string(o,"ownerKeychainService");c.key_tag=kp::json::required_string(o,"secureEnclaveKeyTag");c.service_binary=kp::json::required_string(o,"authorityExecutablePath");return c;}

SecKeyRef load_or_create_key(NSString*tag,bool create){NSData*tag_data=[tag dataUsingEncoding:NSUTF8StringEncoding];NSDictionary*q=@{(__bridge id)kSecClass:(__bridge id)kSecClassKey,(__bridge id)kSecAttrApplicationTag:tag_data,(__bridge id)kSecAttrKeyType:(__bridge id)kSecAttrKeyTypeECSECPrimeRandom,(__bridge id)kSecReturnRef:@YES};CFTypeRef result=nullptr;OSStatus st=SecItemCopyMatching((__bridge CFDictionaryRef)q,&result);if(st==errSecSuccess&&result)return(SecKeyRef)result;if(!create)throw std::runtime_error("secure_enclave_key_missing");CFErrorRef error=nullptr;SecAccessControlRef ac=SecAccessControlCreateWithFlags(kCFAllocatorDefault,kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,kSecAccessControlPrivateKeyUsage,&error);if(!ac)throw std::runtime_error("secure_enclave_access_control_failed:"+cf_error(error));NSDictionary*attrs=@{(__bridge id)kSecAttrKeyType:(__bridge id)kSecAttrKeyTypeECSECPrimeRandom,(__bridge id)kSecAttrKeySizeInBits:@256,(__bridge id)kSecAttrTokenID:(__bridge id)kSecAttrTokenIDSecureEnclave,(__bridge id)kSecPrivateKeyAttrs:@{(__bridge id)kSecAttrIsPermanent:@YES,(__bridge id)kSecAttrApplicationTag:tag_data,(__bridge id)kSecAttrAccessControl:(__bridge id)ac}};SecKeyRef key=SecKeyCreateRandomKey((__bridge CFDictionaryRef)attrs,&error);CFRelease(ac);if(!key)throw std::runtime_error("secure_enclave_key_create_failed:"+cf_error(error));return key;}
std::string public_spki(SecKeyRef private_key){SecKeyRef pub=SecKeyCopyPublicKey(private_key);if(!pub)throw std::runtime_error("public_key_missing");CFErrorRef error=nullptr;CFDataRef raw=SecKeyCopyExternalRepresentation(pub,&error);CFRelease(pub);if(!raw)throw std::runtime_error("public_key_export_failed:"+cf_error(error));const auto*p=CFDataGetBytePtr(raw);const CFIndex n=CFDataGetLength(raw);if(!p||n!=65||p[0]!=0x04){CFRelease(raw);throw std::runtime_error("p256_public_key_shape_invalid");}std::vector<unsigned char>spki={0x30,0x59,0x30,0x13,0x06,0x07,0x2a,0x86,0x48,0xce,0x3d,0x02,0x01,0x06,0x08,0x2a,0x86,0x48,0xce,0x3d,0x03,0x01,0x07,0x03,0x42,0x00};spki.insert(spki.end(),p,p+static_cast<std::size_t>(n));CFRelease(raw);return base64(spki.data(),spki.size());}
class mac_crypto final:public kp::crypto_backend{public:explicit mac_crypto(const config&c):key_(load_or_create_key([NSString stringWithUTF8String:c.key_tag.c_str()],false)),grant_(keychain_secret([NSString stringWithUTF8String:c.grant_service.c_str()])),owner_(keychain_secret([NSString stringWithUTF8String:c.owner_service.c_str()])),public_(public_spki(key_)){CFErrorRef error=nullptr;CFDataRef exported=SecKeyCopyExternalRepresentation(key_,&error);export_denied_=exported==nullptr;if(exported)CFRelease(exported);if(!export_denied_)throw std::runtime_error("secure_enclave_private_export_not_denied");attestation_=kp::sha256_hex(c.key_tag+"|"+public_+"|secure-enclave|private-export-denied");}
 ~mac_crypto()override{if(key_)CFRelease(key_);std::fill(grant_.begin(),grant_.end(),0);std::fill(owner_.begin(),owner_.end(),0);}
 std::string hmac_sha256_hex(std::string_view purpose,std::string_view key_id,std::string_view message)override{const auto&key=key_id.find("owner")!=std::string_view::npos?owner_:grant_;std::string payload;payload.reserve(purpose.size()+message.size());payload.append(purpose);payload.append(message);const auto out=legacy_hmac_sha256(key,payload);return kp::hex_bytes(out.data(),out.size());}
 kp::signature_result sign_effect_permit(std::string_view canonical)override{kp::sha256_state h;h.update(canonical);auto digest=h.finish();CFErrorRef error=nullptr;CFDataRef sig=SecKeyCreateSignature(key_,kSecKeyAlgorithmECDSASignatureDigestX962SHA256,(__bridge CFDataRef)data(std::string_view(reinterpret_cast<const char*>(digest.data()),digest.size())),&error);if(!sig)throw std::runtime_error("secure_enclave_sign_failed:"+cf_error(error));const CFIndex sig_length=CFDataGetLength(sig);if(sig_length<0){CFRelease(sig);throw std::runtime_error("secure_enclave_signature_length_invalid");}std::string encoded=base64(CFDataGetBytePtr(sig),static_cast<std::size_t>(sig_length));CFRelease(sig);return{"ecdsa-p256-sha256","p1a-permit-macos",encoded,public_,"apple-secure-enclave",attestation_,true,export_denied_};}
 kp::json::value public_description()const override{return kp::json::value(kp::json::value::object{{"algorithm",kp::json::value("ecdsa-p256-sha256")},{"keyId",kp::json::value("p1a-permit-macos")},{"publicKeySpkiBase64",kp::json::value(public_)},{"provider",kp::json::value("apple-secure-enclave")},{"providerAttestationSha256",kp::json::value(attestation_)},{"nonExportable",kp::json::value(true)},{"privateExportDenied",kp::json::value(export_denied_)}});}
 private:SecKeyRef key_;std::vector<unsigned char>grant_,owner_;std::string public_,attestation_;bool export_denied_=false;};

class posix_state final:public kp::state_backend{public:posix_state(std::filesystem::path s,std::filesystem::path a,std::filesystem::path r,std::filesystem::path approvals):state_(std::move(s)),audit_(std::move(a)),rev_(std::move(r)),approvals_(std::move(approvals)){std::filesystem::create_directories(state_.parent_path());fd_=::open(state_.c_str(),O_RDWR|O_CREAT|O_CLOEXEC,0600);if(fd_<0||::fchmod(fd_,0600)!=0||::flock(fd_,LOCK_EX|LOCK_NB)!=0)throw std::runtime_error("state_lock_failed");load();++generation_;append("GENERATION\t"+std::to_string(generation_));}~posix_state()override{if(fd_>=0){::flock(fd_,LOCK_UN);::close(fd_);}}
 std::uint64_t revocation_epoch()const override{rev();return epoch_;}bool capability_revoked(std::string_view id)const override{rev();return revoked_.contains(std::string(id));}bool nonce_consumed(std::string_view n)const override{return nonces_.contains(std::string(n));}std::uint64_t grant_use_count(std::string_view id)const override{auto i=uses_.find(std::string(id));return i==uses_.end()?0:i->second;}std::string audit_head_sha256()const override{return head_;}bool permit_exists(std::string_view id)const override{return permits_.contains(std::string(id));}
 kp::json::value owner_approval(std::string_view id)const override{if(auto it=persisted_approvals_.find(std::string(id));it!=persisted_approvals_.end())return kp::json::parse(it->second);auto v=kp::json::parse(kp::read_text_file(approvals_));const auto&o=v.as_object();for(const auto&row:kp::json::required_array(o,"approvals")){const auto&r=row.as_object();if(kp::json::required_string(r,"approvalId")==id)return row;}throw std::runtime_error("owner_approval_missing");}
 void commit_owner_approval(std::string_view id,std::string_view canonical)override{if(persisted_approvals_.contains(std::string(id)))throw std::runtime_error("owner_approval_replay");append("APPROVAL\t"+std::string(id)+"\t"+std::string(canonical));persisted_approvals_[std::string(id)]=std::string(canonical);}
 void commit_authorization(std::string_view nonce,std::string_view grant,std::uint64_t use,std::string_view permit,std::string_view audit,std::string_view digest)override{append("USE\t"+std::string(grant)+"\t"+std::to_string(use)+"\t"+std::string(nonce));append("PERMIT\t"+std::string(permit));append_audit(audit);append("AUDIT\t"+std::string(digest));nonces_.insert(std::string(nonce));uses_[std::string(grant)]=use;permits_.insert(std::string(permit));head_=digest;}
 void commit_outcome(std::string_view permit,std::string_view c,std::string_view d)override{if(!permits_.contains(std::string(permit)))throw std::runtime_error("outcome_unknown_permit");append_audit(c);append("AUDIT\t"+std::string(d));head_=d;}
 std::uint64_t service_generation()const override{return generation_;}
 void begin_behavior_session(std::string_view id,std::string_view binding)override{if(behavior_start_.contains(std::string(id)))throw std::runtime_error("behavior_session_replay");append("BEHAVIOR_BEGIN\t"+std::string(id)+"\t"+std::to_string(generation_)+"\t"+std::string(binding));behavior_start_[std::string(id)]={generation_,std::string(binding)};}
 void record_behavior_event(std::string_view id,std::string_view event,std::string_view evidence)override{if(!behavior_start_.contains(std::string(id))||!kp::valid_identifier(event)||!kp::valid_hex64(evidence))throw std::runtime_error("behavior_event_invalid");auto&events=behavior_events_[std::string(id)];if(events.contains(std::string(event))){if(events[std::string(event)]!=evidence)throw std::runtime_error("behavior_event_conflict");return;}append("BEHAVIOR_EVENT\t"+std::string(id)+"\t"+std::string(event)+"\t"+std::string(evidence));events[std::string(event)]=std::string(evidence);}
 kp::json::value behavior_session(std::string_view id)const override{auto it=behavior_start_.find(std::string(id));if(it==behavior_start_.end())throw std::runtime_error("behavior_session_missing");kp::json::value::array rows;auto events=behavior_events_.find(std::string(id));if(events!=behavior_events_.end())for(const auto&[event,digest]:events->second)rows.emplace_back(kp::json::value::object{{"event",kp::json::value(event)},{"evidenceSha256",kp::json::value(digest)}});return kp::json::value(kp::json::value::object{{"behaviorSessionId",kp::json::value(std::string(id))},{"startGeneration",kp::json::value(static_cast<std::int64_t>(it->second.first))},{"currentGeneration",kp::json::value(static_cast<std::int64_t>(generation_))},{"exactRunBindingSha256",kp::json::value(it->second.second)},{"events",kp::json::value(rows)}});}
 private:std::filesystem::path state_,audit_,rev_,approvals_;int fd_=-1;std::unordered_set<std::string>nonces_,permits_;std::unordered_map<std::string,std::uint64_t>uses_;std::unordered_map<std::string,std::string>persisted_approvals_;mutable std::uint64_t epoch_=0;mutable std::unordered_set<std::string>revoked_;std::string head_=std::string(64,'0');std::uint64_t generation_=0;std::unordered_map<std::string,std::pair<std::uint64_t,std::string>>behavior_start_;std::unordered_map<std::string,std::map<std::string,std::string>>behavior_events_;void load(){std::ifstream in(state_);std::string line;while(std::getline(in,line)){std::vector<std::string>f;std::size_t p=0;while(true){auto q=line.find('\t',p);f.push_back(line.substr(p,q==std::string::npos?q:q-p));if(q==std::string::npos)break;p=q+1;}if(f.size()==4&&f[0]=="USE"){uses_[f[1]]=std::stoull(f[2]);nonces_.insert(f[3]);}else if(f.size()==2&&f[0]=="PERMIT")permits_.insert(f[1]);else if(f.size()==2&&f[0]=="AUDIT")head_=f[1];else if(f.size()==3&&f[0]=="APPROVAL")persisted_approvals_[f[1]]=f[2];else if(f.size()==2&&f[0]=="GENERATION")generation_=std::max<std::uint64_t>(generation_,std::stoull(f[1]));else if(f.size()==4&&f[0]=="BEHAVIOR_BEGIN"&&kp::valid_hex64(f[3]))behavior_start_[f[1]]={std::stoull(f[2]),f[3]};else if(f.size()==4&&f[0]=="BEHAVIOR_EVENT"&&kp::valid_hex64(f[3]))behavior_events_[f[1]][f[2]]=f[3];}}void rev()const{auto v=kp::json::parse(kp::read_text_file(rev_));const auto&o=v.as_object();epoch_=static_cast<std::uint64_t>(kp::json::required_int(o,"revocationEpoch"));revoked_.clear();for(const auto&x:kp::json::required_array(o,"revokedCapabilities"))if(x.is_string())revoked_.insert(x.as_string());}void append(const std::string&line){::lseek(fd_,0,SEEK_END);auto row=line+"\n";if(::write(fd_,row.data(),row.size())!=static_cast<ssize_t>(row.size())||::fsync(fd_)!=0)throw std::runtime_error("state_persist_failed");}void append_audit(std::string_view line){int f=::open(audit_.c_str(),O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC,0600);if(f<0)throw std::runtime_error("audit_open_failed");std::string row(line);row.push_back('\n');bool ok=::write(f,row.data(),row.size())==static_cast<ssize_t>(row.size())&&::fsync(f)==0;::close(f);if(!ok)throw std::runtime_error("audit_persist_failed");}};

struct context{config cfg;kp::authority_config core_cfg;mac_crypto crypto;posix_state state;kp::authority_core core;explicit context(config c,std::filesystem::path path):cfg(std::move(c)),core_cfg(kp::load_authority_config(path)),crypto(cfg),state(cfg.state,cfg.audit,cfg.revocations,cfg.approvals),core(core_cfg,crypto,state){}};
void reply(xpc_object_t event,xpc_object_t peer,std::string_view body){xpc_object_t r=xpc_dictionary_create_reply(event);if(!r)r=xpc_dictionary_create(nullptr,nullptr,0);xpc_dictionary_set_data(r,"response",body.data(),body.size());xpc_connection_send_message(peer,r);}
using xpc_get_audit_token_fn=void(*)(xpc_connection_t,audit_token_t*);
bool copy_peer_audit_token(xpc_connection_t peer,audit_token_t&token){void*symbol=dlsym(RTLD_DEFAULT,"xpc_connection_get_audit_token");if(!symbol)return false;xpc_get_audit_token_fn function=nullptr;static_assert(sizeof(function)==sizeof(symbol));std::memcpy(&function,&symbol,sizeof(function));if(!function)return false;function(peer,&token);return true;}
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
bool peer_matches_requirement(xpc_connection_t peer,const std::string& requirement_text){audit_token_t token{};if(!copy_peer_audit_token(peer,token))return false;CFDataRef audit=CFDataCreate(kCFAllocatorDefault,reinterpret_cast<const UInt8*>(&token),static_cast<CFIndex>(sizeof(token)));if(!audit)return false;const void*keys[]={kSecGuestAttributeAudit};const void*values[]={audit};CFDictionaryRef attrs=CFDictionaryCreate(kCFAllocatorDefault,keys,values,static_cast<CFIndex>(1),&kCFTypeDictionaryKeyCallBacks,&kCFTypeDictionaryValueCallBacks);SecCodeRef guest=nullptr;const OSStatus copied=attrs?SecCodeCopyGuestWithAttributes(nullptr,attrs,kSecCSDefaultFlags,&guest):errSecParam;CFStringRef text=CFStringCreateWithCString(kCFAllocatorDefault,requirement_text.c_str(),kCFStringEncodingUTF8);SecRequirementRef requirement=nullptr;const OSStatus parsed=text?SecRequirementCreateWithString(text,kSecCSDefaultFlags,&requirement):errSecParam;const bool ok=copied==errSecSuccess&&parsed==errSecSuccess&&guest&&requirement&&SecCodeCheckValidity(guest,kSecCSStrictValidate|kSecCSCheckAllArchitectures,requirement)==errSecSuccess;if(requirement)CFRelease(requirement);if(text)CFRelease(text);if(guest)CFRelease(guest);if(attrs)CFRelease(attrs);CFRelease(audit);return ok;}
#pragma clang diagnostic pop
void handle_peer(xpc_connection_t peer,std::shared_ptr<context>ctx){const bool desktop=peer_matches_requirement(peer,ctx->cfg.desktop_requirement);const bool worker=peer_matches_requirement(peer,ctx->cfg.worker_requirement);if(!desktop&&!worker){xpc_connection_cancel(peer);return;}xpc_connection_set_event_handler(peer,^(xpc_object_t event){if(xpc_get_type(event)!=XPC_TYPE_DICTIONARY)return;const void*bytes=nullptr;size_t size=0;bytes=xpc_dictionary_get_data(event,"request",&size);if(!bytes||size==0||size>static_cast<size_t>(ctx->core_cfg.max_request_bytes)){reply(event,peer,kp::json::canonical(kp::denied_response("frame_size_invalid")));return;}try{pid_t pid=xpc_connection_get_pid(peer);uid_t uid=xpc_connection_get_euid(peer);au_asid_t asid=xpc_connection_get_asid(peer);auto request=kp::json::parse(std::string_view(static_cast<const char*>(bytes),size));kp::peer_identity identity{"macos",std::to_string(uid),"code-signing-requirement",worker?ctx->cfg.worker_requirement:ctx->cfg.desktop_requirement,std::to_string(asid),static_cast<std::uint64_t>(pid),desktop&&!worker,worker};if(worker){ctx->core.note_worker_denial(kp::json::required_string(request.as_object(),"behaviorSessionId"),identity,kp::json::required_string(request.as_object(),"workerIdentitySha256"));reply(event,peer,kp::json::canonical(kp::denied_response("worker_principal_denied")));return;}reply(event,peer,kp::json::canonical(ctx->core.handle(request,identity)));}catch(const std::exception&e){reply(event,peer,kp::json::canonical(kp::denied_response(e.what())));}});xpc_connection_activate(peer);}
int provision(const config&c,std::string&grant_hex,std::string&owner_hex){SecKeyRef key=load_or_create_key([NSString stringWithUTF8String:c.key_tag.c_str()],true);CFRelease(key);auto decode=[](std::string_view h){if(h.size()<32||h.size()%2)throw std::runtime_error("secret_hex_invalid");NSMutableData*d=[NSMutableData dataWithLength:h.size()/2];auto*out=static_cast<unsigned char*>(d.mutableBytes);for(std::size_t i=0;i<h.size()/2;++i){auto cv=[](char x)->int{if(x>='0'&&x<='9')return x-'0';if(x>='a'&&x<='f')return 10+x-'a';if(x>='A'&&x<='F')return 10+x-'A';return-1;};int a=cv(h[i*2]),b=cv(h[i*2+1]);if(a<0||b<0)throw std::runtime_error("secret_hex_invalid");out[i]=static_cast<unsigned char>((a<<4)|b);}return d;};@autoreleasepool{NSData*grant=decode(grant_hex);NSData*owner=decode(owner_hex);store_keychain_secret([NSString stringWithUTF8String:c.grant_service.c_str()],grant,c.service_binary);store_keychain_secret([NSString stringWithUTF8String:c.owner_service.c_str()],owner,c.service_binary);}std::fill(grant_hex.begin(),grant_hex.end(),'\0');std::fill(owner_hex.begin(),owner_hex.end(),'\0');return 0;}
} // namespace

int main(int argc,const char**argv){@autoreleasepool{try{if(argc==2&&std::string(argv[1])=="--source-self-test"){std::cout<<"{\"status\":\"passed\",\"platform\":\"macos\",\"authorityCore\":\"v2\",\"completionEligible\":false}\n";return 0;}if(argc<2)throw std::runtime_error("config_path_required");std::filesystem::path config_path=argv[1];auto cfg=load_config(config_path);if(argc==3&&std::string(argv[2])=="--provision-stdin"){std::string grant,owner;if(!std::getline(std::cin,grant)||!std::getline(std::cin,owner))throw std::runtime_error("provisioning_secret_stdin_failed");try{return provision(cfg,grant,owner);}catch(...){std::fill(grant.begin(),grant.end(),'\0');std::fill(owner.begin(),owner.end(),'\0');throw;}}auto ctx=std::make_shared<context>(cfg,config_path);xpc_connection_t listener=xpc_connection_create_mach_service(cfg.mach_service.c_str(),dispatch_get_main_queue(),XPC_CONNECTION_MACH_SERVICE_LISTENER);if(!listener)throw std::runtime_error("xpc_listener_create_failed");xpc_connection_set_event_handler(listener,^(xpc_object_t peer){if(xpc_get_type(peer)==XPC_TYPE_CONNECTION)handle_peer((xpc_connection_t)peer,ctx);});xpc_connection_activate(listener);dispatch_main();return 0;}catch(const std::exception&e){std::cerr<<"P1A macOS authority fatal: "<<e.what()<<"\n";return 1;}}}
