#include "authority_core_v2.hpp"
// Production secrets arrive only through systemd credentials; no PEM/key path is accepted.

#include <fcntl.h>
#include <openssl/core_names.h>
#include <openssl/encoder.h>
#include <openssl/evp.h>
#include <openssl/params.h>
#include <openssl/store.h>
#include <poll.h>
#include <signal.h>
#include <sys/file.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/un.h>
#include <unistd.h>

#include <array>
#include <atomic>
#include <cerrno>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace kp = kristin::p1a;
namespace {
std::atomic<bool> g_stop{false};
void on_signal(int) { g_stop.store(true); }

struct fd_handle { int value=-1; fd_handle()=default; explicit fd_handle(int v):value(v){} ~fd_handle(){if(value>=0)::close(value);} fd_handle(const fd_handle&)=delete;fd_handle& operator=(const fd_handle&)=delete;fd_handle(fd_handle&&o)noexcept:value(o.value){o.value=-1;} };
struct pkey_deleter { void operator()(EVP_PKEY* p)const{EVP_PKEY_free(p);} }; using pkey_ptr=std::unique_ptr<EVP_PKEY,pkey_deleter>;

struct options final {
  std::filesystem::path socket_path,config_path,state_path,audit_path,revocations_path,approvals_path,grant_credential,owner_credential;
  std::string key_uri,desktop_exe_sha256;uid_t desktop_uid=std::numeric_limits<uid_t>::max(),worker_uid=std::numeric_limits<uid_t>::max(),service_uid=std::numeric_limits<uid_t>::max();gid_t service_gid=std::numeric_limits<gid_t>::max(),worker_gid=std::numeric_limits<gid_t>::max();int max_requests=0;bool source_self_test=false;
};
std::string take(int& i,int argc,char**argv){if(++i>=argc)throw std::runtime_error("missing_argument_value");return argv[i];}
options parse(int argc,char**argv){options o;for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--socket")o.socket_path=take(i,argc,argv);else if(a=="--config")o.config_path=take(i,argc,argv);else if(a=="--state")o.state_path=take(i,argc,argv);else if(a=="--audit")o.audit_path=take(i,argc,argv);else if(a=="--revocations")o.revocations_path=take(i,argc,argv);else if(a=="--approvals")o.approvals_path=take(i,argc,argv);else if(a=="--permit-key-uri")o.key_uri=take(i,argc,argv);else if(a=="--grant-hmac-credential")o.grant_credential=take(i,argc,argv);else if(a=="--owner-hmac-credential")o.owner_credential=take(i,argc,argv);else if(a=="--desktop-uid")o.desktop_uid=static_cast<uid_t>(std::stoul(take(i,argc,argv)));else if(a=="--worker-uid")o.worker_uid=static_cast<uid_t>(std::stoul(take(i,argc,argv)));else if(a=="--service-uid")o.service_uid=static_cast<uid_t>(std::stoul(take(i,argc,argv)));else if(a=="--service-gid")o.service_gid=static_cast<gid_t>(std::stoul(take(i,argc,argv)));else if(a=="--worker-gid")o.worker_gid=static_cast<gid_t>(std::stoul(take(i,argc,argv)));else if(a=="--desktop-exe-sha256")o.desktop_exe_sha256=take(i,argc,argv);else if(a=="--max-requests")o.max_requests=std::stoi(take(i,argc,argv));else if(a=="--source-self-test")o.source_self_test=true;else throw std::runtime_error("unknown_argument:"+a);}
  if(o.source_self_test)return o;
  if(o.socket_path.empty()||o.config_path.empty()||o.state_path.empty()||o.audit_path.empty()||o.revocations_path.empty()||o.approvals_path.empty()||o.key_uri.empty()||o.grant_credential.empty()||o.owner_credential.empty()||o.desktop_uid==std::numeric_limits<uid_t>::max()||o.worker_uid==std::numeric_limits<uid_t>::max()||o.service_uid==std::numeric_limits<uid_t>::max()||o.service_gid==std::numeric_limits<gid_t>::max()||o.worker_gid==std::numeric_limits<gid_t>::max()||o.desktop_uid==o.worker_uid||o.service_uid==o.worker_uid||o.service_uid==o.desktop_uid||!kp::valid_hex64(o.desktop_exe_sha256))throw std::runtime_error("invalid_or_incomplete_configuration");
  if(!(o.key_uri.rfind("pkcs11:",0)==0||o.key_uri.rfind("tpm2:",0)==0))throw std::runtime_error("non_exportable_provider_uri_required");
  return o;}

void require_secure_regular(const std::filesystem::path&p,bool root_owned=true,gid_t readable_group=static_cast<gid_t>(-1)){struct stat st{};if(::lstat(p.c_str(),&st)!=0||!S_ISREG(st.st_mode)||S_ISLNK(st.st_mode))throw std::runtime_error("secure_file_missing:"+p.string());if(root_owned&&st.st_uid!=0)throw std::runtime_error("secure_file_not_root_owned:"+p.string());if((st.st_mode&(S_IWGRP|S_IRWXO))!=0)throw std::runtime_error("secure_file_permissions_too_wide:"+p.string());if((st.st_mode&S_IRGRP)!=0&&(readable_group==static_cast<gid_t>(-1)||st.st_gid!=readable_group))throw std::runtime_error("secure_file_group_invalid:"+p.string());}
std::vector<unsigned char> read_secret(const std::filesystem::path&p){struct stat st{};if(::lstat(p.c_str(),&st)!=0||!S_ISREG(st.st_mode)||S_ISLNK(st.st_mode)||(st.st_mode&(S_IRWXG|S_IRWXO))!=0||(st.st_uid!=0&&st.st_uid!=::geteuid()))throw std::runtime_error("credential_permissions_invalid");const auto s=kp::read_text_file(p,4096);if(s.size()<16||s.size()>1024)throw std::runtime_error("credential_size_invalid");return std::vector<unsigned char>(s.begin(),s.end());}
std::string base64(const unsigned char*p,std::size_t n){std::string out(4*((n+2)/3),'\0');int w=EVP_EncodeBlock(reinterpret_cast<unsigned char*>(out.data()),p,static_cast<int>(n));if(w<0)throw std::runtime_error("base64_failed");out.resize(static_cast<std::size_t>(w));return out;}
std::string sha256_file(const std::filesystem::path&p){std::ifstream in(p,std::ios::binary);if(!in)throw std::runtime_error("file_hash_open_failed");kp::sha256_state h;std::array<char,65536>b{};while(in){in.read(b.data(),b.size());auto n=in.gcount();if(n>0)h.update(b.data(),static_cast<std::size_t>(n));}if(in.bad())throw std::runtime_error("file_hash_read_failed");auto d=h.finish();return kp::hex_bytes(d.data(),d.size());}
std::string proc_exe(pid_t pid){std::array<char,4096>b{};auto link=std::filesystem::path("/proc")/std::to_string(pid)/"exe";auto n=::readlink(link.c_str(),b.data(),b.size()-1);if(n<=0)throw std::runtime_error("peer_executable_unavailable");return std::string(b.data(),static_cast<std::size_t>(n));}

pkey_ptr load_provider_key(const std::string&uri){OSSL_STORE_CTX*ctx=OSSL_STORE_open(uri.c_str(),nullptr,nullptr,nullptr,nullptr);if(!ctx)throw std::runtime_error("provider_key_open_failed");EVP_PKEY*key=nullptr;while(!OSSL_STORE_eof(ctx)){OSSL_STORE_INFO*info=OSSL_STORE_load(ctx);if(!info){if(OSSL_STORE_error(ctx))break;continue;}if(OSSL_STORE_INFO_get_type(info)==OSSL_STORE_INFO_PKEY){key=OSSL_STORE_INFO_get1_PKEY(info);OSSL_STORE_INFO_free(info);break;}OSSL_STORE_INFO_free(info);}OSSL_STORE_close(ctx);if(!key)throw std::runtime_error("provider_private_key_missing");if(EVP_PKEY_base_id(key)!=EVP_PKEY_EC) {EVP_PKEY_free(key);throw std::runtime_error("provider_ecdsa_p256_key_required");}char group[80]{};std::size_t n=0;if(EVP_PKEY_get_utf8_string_param(key,OSSL_PKEY_PARAM_GROUP_NAME,group,sizeof(group),&n)!=1||std::string(group)!="prime256v1"){EVP_PKEY_free(key);throw std::runtime_error("provider_ecdsa_p256_group_required");}return pkey_ptr(key);}
bool private_export_denied(EVP_PKEY*key){OSSL_ENCODER_CTX*ctx=OSSL_ENCODER_CTX_new_for_pkey(key,EVP_PKEY_KEYPAIR,"DER","PrivateKeyInfo",nullptr);if(!ctx)return true;unsigned char*data=nullptr;std::size_t size=0;const int ok=OSSL_ENCODER_to_data(ctx,&data,&size);OPENSSL_clear_free(data,size);OSSL_ENCODER_CTX_free(ctx);return ok!=1;}
std::string public_spki(EVP_PKEY*key){unsigned char*der=nullptr;int n=i2d_PUBKEY(key,&der);if(n<=0)throw std::runtime_error("public_key_export_failed");std::string out=base64(der,static_cast<std::size_t>(n));OPENSSL_free(der);return out;}

class linux_crypto final:public kp::crypto_backend{
 public:linux_crypto(std::string uri,std::filesystem::path grant,std::filesystem::path owner):uri_(std::move(uri)),key_(load_provider_key(uri_)),grant_(read_secret(grant)),owner_(read_secret(owner)),export_denied_(private_export_denied(key_.get())),public_(public_spki(key_.get())){if(!export_denied_)throw std::runtime_error("provider_private_key_exportable");attestation_=kp::sha256_hex(uri_+"|"+public_+"|private-export-denied");}
 ~linux_crypto()override{OPENSSL_cleanse(grant_.data(),grant_.size());OPENSSL_cleanse(owner_.data(),owner_.size());}
 std::string hmac_sha256_hex(std::string_view purpose,std::string_view key_id,std::string_view message)override{if(!kp::valid_identifier(key_id))throw std::runtime_error("hmac_key_id_invalid");const auto&key=kp::hmac_secret_for_purpose(purpose)==kp::hmac_secret_kind::owner_approval?owner_:grant_;EVP_MAC*mac=EVP_MAC_fetch(nullptr,"HMAC",nullptr);if(!mac)throw std::runtime_error("hmac_fetch_failed");EVP_MAC_CTX*ctx=EVP_MAC_CTX_new(mac);EVP_MAC_free(mac);if(!ctx)throw std::runtime_error("hmac_ctx_failed");char digest_name[]="SHA256";OSSL_PARAM params[]={OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST,digest_name,0),OSSL_PARAM_construct_end()};std::array<unsigned char,32>out{};std::size_t out_len=0;bool ok=EVP_MAC_init(ctx,key.data(),key.size(),params)==1&&EVP_MAC_update(ctx,reinterpret_cast<const unsigned char*>(purpose.data()),purpose.size())==1&&EVP_MAC_update(ctx,reinterpret_cast<const unsigned char*>(message.data()),message.size())==1&&EVP_MAC_final(ctx,out.data(),&out_len,out.size())==1;EVP_MAC_CTX_free(ctx);if(!ok||out_len!=32)throw std::runtime_error("hmac_failed");return kp::hex_bytes(out.data(),out_len);}
 kp::signature_result sign_effect_permit(std::string_view canonical)override{auto digest_hex=kp::sha256_hex(canonical);std::array<unsigned char,32>digest{};for(std::size_t i=0;i<digest.size();++i)digest[i]=static_cast<unsigned char>(std::stoi(digest_hex.substr(i*2,2),nullptr,16));EVP_PKEY_CTX*ctx=EVP_PKEY_CTX_new(key_.get(),nullptr);if(!ctx)throw std::runtime_error("sign_ctx_failed");std::size_t n=0;bool ok=EVP_PKEY_sign_init(ctx)==1&&EVP_PKEY_CTX_set_signature_md(ctx,EVP_sha256())==1&&EVP_PKEY_sign(ctx,nullptr,&n,digest.data(),digest.size())==1;std::vector<unsigned char>sig(n);ok=ok&&EVP_PKEY_sign(ctx,sig.data(),&n,digest.data(),digest.size())==1;EVP_PKEY_CTX_free(ctx);if(!ok)throw std::runtime_error("provider_sign_failed");sig.resize(n);return {"ecdsa-p256-sha256","p1a-permit-linux",base64(sig.data(),sig.size()),public_,uri_.substr(0,uri_.find(':')),attestation_,true,export_denied_};}
 kp::json::value public_description()const override{return kp::json::value(kp::json::value::object{{"algorithm",kp::json::value("ecdsa-p256-sha256")},{"keyId",kp::json::value("p1a-permit-linux")},{"publicKeySpkiBase64",kp::json::value(public_)},{"provider",kp::json::value(uri_.substr(0,uri_.find(':')))},{"providerAttestationSha256",kp::json::value(attestation_)},{"nonExportable",kp::json::value(true)},{"privateExportDenied",kp::json::value(export_denied_)}});}
 private:std::string uri_;pkey_ptr key_;std::vector<unsigned char>grant_,owner_;bool export_denied_;std::string public_,attestation_;
};

class file_state final:public kp::state_backend{
 public:file_state(std::filesystem::path state,std::filesystem::path audit,std::filesystem::path revocations,std::filesystem::path approvals):state_(std::move(state)),audit_(std::move(audit)),revocations_(std::move(revocations)),approvals_(std::move(approvals)){std::filesystem::create_directories(state_.parent_path());fd_=::open(state_.c_str(),O_RDWR|O_CREAT|O_CLOEXEC,0600);if(fd_<0||::fchmod(fd_,0600)!=0||::flock(fd_,LOCK_EX|LOCK_NB)!=0)throw std::runtime_error("authority_state_lock_failed");load();++generation_;append_state("GENERATION\t"+std::to_string(generation_));}
 ~file_state()override{if(fd_>=0){::flock(fd_,LOCK_UN);::close(fd_);}}
 std::uint64_t revocation_epoch()const override{load_revocations();return epoch_;}bool capability_revoked(std::string_view id)const override{load_revocations();return revoked_.contains(std::string(id));}
 bool nonce_consumed(std::string_view n)const override{return nonces_.contains(std::string(n));}std::uint64_t grant_use_count(std::string_view id)const override{auto i=uses_.find(std::string(id));return i==uses_.end()?0:i->second;}std::string audit_head_sha256()const override{return audit_head_;}bool permit_exists(std::string_view id)const override{return permits_.contains(std::string(id));}
 kp::json::value owner_approval(std::string_view id)const override{if(auto it=persisted_approvals_.find(std::string(id));it!=persisted_approvals_.end())return kp::json::parse(it->second);auto v=kp::json::parse(kp::read_text_file(approvals_));const auto&o=v.as_object();if(kp::json::required_string(o,"schemaVersion")!="2.0.0")throw std::runtime_error("approval_store_schema_invalid");for(const auto&row:kp::json::required_array(o,"approvals")){const auto&r=row.as_object();if(kp::json::required_string(r,"approvalId")==id)return row;}throw std::runtime_error("owner_approval_missing");}
 void commit_owner_approval(std::string_view id,std::string_view canonical)override{if(persisted_approvals_.contains(std::string(id)))throw std::runtime_error("owner_approval_replay");append_state("APPROVAL\t"+std::string(id)+"\t"+std::string(canonical));persisted_approvals_[std::string(id)]=std::string(canonical);}
 void commit_authorization(std::string_view nonce,std::string_view grant,std::uint64_t use,std::string_view permit,std::string_view audit,std::string_view digest)override{append_state("USE\t"+std::string(grant)+"\t"+std::to_string(use)+"\t"+std::string(nonce));append_state("PERMIT\t"+std::string(permit));append_audit(audit);append_state("AUDIT\t"+std::string(digest));nonces_.insert(std::string(nonce));uses_[std::string(grant)]=use;permits_.insert(std::string(permit));audit_head_=digest;}
 void commit_outcome(std::string_view permit,std::string_view canonical,std::string_view digest)override{if(!permits_.contains(std::string(permit)))throw std::runtime_error("outcome_unknown_permit");append_audit(canonical);append_state("AUDIT\t"+std::string(digest));audit_head_=digest;}
 std::uint64_t service_generation()const override{return generation_;}
 void begin_behavior_session(std::string_view id,std::string_view binding)override{if(behavior_start_.contains(std::string(id)))throw std::runtime_error("behavior_session_replay");append_state("BEHAVIOR_BEGIN\t"+std::string(id)+"\t"+std::to_string(generation_)+"\t"+std::string(binding));behavior_start_[std::string(id)]={generation_,std::string(binding)};}
 void record_behavior_event(std::string_view id,std::string_view event,std::string_view evidence)override{if(!behavior_start_.contains(std::string(id))||!kp::valid_identifier(event)||!kp::valid_hex64(evidence))throw std::runtime_error("behavior_event_invalid");auto&events=behavior_events_[std::string(id)];if(events.contains(std::string(event))){if(events[std::string(event)]!=evidence)throw std::runtime_error("behavior_event_conflict");return;}append_state("BEHAVIOR_EVENT\t"+std::string(id)+"\t"+std::string(event)+"\t"+std::string(evidence));events[std::string(event)]=std::string(evidence);}
 kp::json::value behavior_session(std::string_view id)const override{auto it=behavior_start_.find(std::string(id));if(it==behavior_start_.end())throw std::runtime_error("behavior_session_missing");kp::json::value::array rows;auto events=behavior_events_.find(std::string(id));if(events!=behavior_events_.end())for(const auto&[event,digest]:events->second)rows.emplace_back(kp::json::value::object{{"event",kp::json::value(event)},{"evidenceSha256",kp::json::value(digest)}});return kp::json::value(kp::json::value::object{{"behaviorSessionId",kp::json::value(std::string(id))},{"startGeneration",kp::json::value(static_cast<std::int64_t>(it->second.first))},{"currentGeneration",kp::json::value(static_cast<std::int64_t>(generation_))},{"exactRunBindingSha256",kp::json::value(it->second.second)},{"events",kp::json::value(rows)}});}
 private:std::filesystem::path state_,audit_,revocations_,approvals_;int fd_=-1;std::unordered_set<std::string>nonces_,permits_;std::unordered_map<std::string,std::uint64_t>uses_;std::unordered_map<std::string,std::string>persisted_approvals_;mutable std::uint64_t epoch_=0;mutable std::unordered_set<std::string>revoked_;std::string audit_head_=std::string(64,'0');std::uint64_t generation_=0;std::unordered_map<std::string,std::pair<std::uint64_t,std::string>>behavior_start_;std::unordered_map<std::string,std::map<std::string,std::string>>behavior_events_;
 void load(){if(::lseek(fd_,0,SEEK_SET)<0)throw std::runtime_error("state_seek_failed");std::string all;std::array<char,4096>b{};while(true){auto n=::read(fd_,b.data(),b.size());if(n==0)break;if(n<0){if(errno==EINTR)continue;throw std::runtime_error("state_read_failed");}all.append(b.data(),static_cast<std::size_t>(n));}std::istringstream in(all);std::string line;while(std::getline(in,line)){std::vector<std::string>f;std::size_t p=0;while(true){auto q=line.find('\t',p);f.push_back(line.substr(p,q==std::string::npos?q:q-p));if(q==std::string::npos)break;p=q+1;}if(f.size()==4&&f[0]=="USE"){uses_[f[1]]=std::max<std::uint64_t>(uses_[f[1]],std::stoull(f[2]));nonces_.insert(f[3]);}else if(f.size()==2&&f[0]=="PERMIT")permits_.insert(f[1]);else if(f.size()==2&&f[0]=="AUDIT"&&kp::valid_hex64(f[1]))audit_head_=f[1];else if(f.size()==3&&f[0]=="APPROVAL")persisted_approvals_[f[1]]=f[2];else if(f.size()==2&&f[0]=="GENERATION")generation_=std::max<std::uint64_t>(generation_,std::stoull(f[1]));else if(f.size()==4&&f[0]=="BEHAVIOR_BEGIN"&&kp::valid_hex64(f[3]))behavior_start_[f[1]]={std::stoull(f[2]),f[3]};else if(f.size()==4&&f[0]=="BEHAVIOR_EVENT"&&kp::valid_hex64(f[3]))behavior_events_[f[1]][f[2]]=f[3];}}
 void load_revocations()const{require_secure_regular(revocations_);auto v=kp::json::parse(kp::read_text_file(revocations_));const auto&o=v.as_object();if(kp::json::required_string(o,"schemaVersion")!="2.0.0")throw std::runtime_error("revocation_schema_invalid");epoch_=static_cast<std::uint64_t>(kp::json::required_int(o,"revocationEpoch"));revoked_.clear();for(const auto&x:kp::json::required_array(o,"revokedCapabilities"))if(x.is_string())revoked_.insert(x.as_string());}
 void append_state(const std::string&line){if(::lseek(fd_,0,SEEK_END)<0)throw std::runtime_error("state_seek_end_failed");const auto row=line+"\n";std::size_t off=0;while(off<row.size()){auto n=::write(fd_,row.data()+off,row.size()-off);if(n<0){if(errno==EINTR)continue;throw std::runtime_error("state_write_failed");}off+=static_cast<std::size_t>(n);}if(::fsync(fd_)!=0)throw std::runtime_error("state_fsync_failed");}
 void append_audit(std::string_view line){int f=::open(audit_.c_str(),O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC,0600);if(f<0)throw std::runtime_error("audit_open_failed");::fchmod(f,0600);std::string row(line);row.push_back('\n');bool ok=::write(f,row.data(),row.size())==static_cast<ssize_t>(row.size())&&::fsync(f)==0;::close(f);if(!ok)throw std::runtime_error("audit_write_failed");}
};

std::string read_frame(int fd,std::size_t limit){std::array<unsigned char,4>h{};std::size_t off=0;while(off<h.size()){auto n=::recv(fd,h.data()+off,h.size()-off,0);if(n<=0)throw std::runtime_error("frame_header_read_failed");off+=n;}std::uint32_t size=(std::uint32_t(h[0])<<24)|(std::uint32_t(h[1])<<16)|(std::uint32_t(h[2])<<8)|h[3];if(size==0||size>limit)throw std::runtime_error("frame_size_invalid");std::string out(size,'\0');off=0;while(off<size){auto n=::recv(fd,out.data()+off,size-off,0);if(n<=0)throw std::runtime_error("frame_body_read_failed");off+=n;}return out;}
void write_frame(int fd,std::string_view body){std::array<unsigned char,4>h{static_cast<unsigned char>(body.size()>>24),static_cast<unsigned char>(body.size()>>16),static_cast<unsigned char>(body.size()>>8),static_cast<unsigned char>(body.size())};for(auto part:{std::string_view(reinterpret_cast<const char*>(h.data()),h.size()),body}){std::size_t off=0;while(off<part.size()){auto n=::send(fd,part.data()+off,part.size()-off,MSG_NOSIGNAL);if(n<0){if(errno==EINTR)continue;throw std::runtime_error("frame_write_failed");}off+=n;}}}

int source_self_test(){auto v=kp::json::parse("{\"a\":1,\"b\":[true,false],\"z\":\"ok\"}");if(kp::sha256_hex(kp::json::canonical(v)).size()!=64)return 2;std::cout<<"P1A Linux V63 source core PASS\n";return 0;}
} // namespace

int main(int argc,char**argv)try{auto o=parse(argc,argv);if(o.source_self_test)return source_self_test();if(::geteuid()!=0&&::geteuid()!=o.service_uid)throw std::runtime_error("authority_service_identity_mismatch");require_secure_regular(o.config_path,true,o.service_gid);require_secure_regular(o.revocations_path,true,o.service_gid);require_secure_regular(o.approvals_path,true,o.service_gid);auto cfg=kp::load_authority_config(o.config_path);linux_crypto crypto(o.key_uri,o.grant_credential,o.owner_credential);file_state state(o.state_path,o.audit_path,o.revocations_path,o.approvals_path);kp::authority_core core(std::move(cfg),crypto,state);
 std::filesystem::create_directories(o.socket_path.parent_path());::unlink(o.socket_path.c_str());fd_handle server(::socket(AF_UNIX,SOCK_STREAM|SOCK_CLOEXEC,0));if(server.value<0)throw std::runtime_error("socket_create_failed");sockaddr_un addr{};addr.sun_family=AF_UNIX;if(o.socket_path.string().size()>=sizeof(addr.sun_path))throw std::runtime_error("socket_path_too_long");std::strncpy(addr.sun_path,o.socket_path.c_str(),sizeof(addr.sun_path)-1);if(::bind(server.value,reinterpret_cast<sockaddr*>(&addr),sizeof(addr))!=0)throw std::runtime_error("socket_bind_failed:"+std::string(std::strerror(errno)));if(::chown(o.socket_path.c_str(),o.desktop_uid,o.worker_gid)!=0||::chmod(o.socket_path.c_str(),0660)!=0)throw std::runtime_error("socket_acl_failed");if(::listen(server.value,16)!=0)throw std::runtime_error("socket_listen_failed");::signal(SIGTERM,on_signal);::signal(SIGINT,on_signal);std::cout<<"READY "<<o.socket_path<<"\n";int handled=0;while(!g_stop.load()&&(o.max_requests<=0||handled<o.max_requests)){pollfd pfd{server.value,POLLIN,0};int pr=::poll(&pfd,1,250);if(pr<0){if(errno==EINTR)continue;throw std::runtime_error("poll_failed");}if(pr==0)continue;fd_handle client(::accept4(server.value,nullptr,nullptr,SOCK_CLOEXEC));if(client.value<0){if(errno==EINTR)continue;throw std::runtime_error("accept_failed");}++handled;try{ucred cred{};socklen_t len=sizeof(cred);if(::getsockopt(client.value,SOL_SOCKET,SO_PEERCRED,&cred,&len)!=0||len!=sizeof(cred))throw std::runtime_error("peer_credentials_unavailable");auto exe=proc_exe(cred.pid);auto exe_hash=sha256_file(exe);if(cred.uid==o.worker_uid){timeval timeout{2,0};::setsockopt(client.value,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));auto req=kp::json::parse(read_frame(client.value,static_cast<std::size_t>(cfg.max_request_bytes)));const auto session=kp::json::required_string(req.as_object(),"behaviorSessionId");kp::peer_identity worker{"linux",std::to_string(cred.uid),exe_hash,exe,std::to_string(::getsid(cred.pid)),static_cast<std::uint64_t>(cred.pid),false,true};core.note_worker_denial(session,worker,kp::json::required_string(req.as_object(),"workerIdentitySha256"));throw std::runtime_error("worker_principal_denied");}if(cred.uid!=o.desktop_uid)throw std::runtime_error("desktop_principal_required");if(exe_hash!=o.desktop_exe_sha256)throw std::runtime_error("desktop_executable_identity_mismatch");kp::peer_identity peer{"linux",std::to_string(cred.uid),exe_hash,exe,std::to_string(::getsid(cred.pid)),static_cast<std::uint64_t>(cred.pid),true,false};auto req=kp::json::parse(read_frame(client.value,static_cast<std::size_t>(cfg.max_request_bytes)));write_frame(client.value,kp::json::canonical(core.handle(req,peer)));}catch(const std::exception&e){write_frame(client.value,kp::json::canonical(kp::denied_response(e.what())));}}
 ::unlink(o.socket_path.c_str());return 0;}catch(const std::exception&e){std::cerr<<"P1A Linux authority fatal: "<<e.what()<<"\n";return 1;}
