
#include "../common/p1a_connector.h"
#include "../../native/common/strict_json.hpp"
#import <Foundation/Foundation.h>
#include <xpc/xpc.h>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <stdexcept>
#include <string>
#include <string_view>
namespace {namespace j=kristin::p1a::json;std::mutex g_mu;std::string g_service,g_response;std::size_t g_max=4*1024*1024;
void set_error(std::string_view code){g_response=j::canonical(j::value(j::value::object{{"schemaVersion",j::value("2.0.0")},{"status",j::value("transport-error")},{"errorCode",j::value(std::string(code))}}));}
std::string transact(std::string_view request){if(g_service.empty())throw std::runtime_error("connector_not_configured");xpc_connection_t connection=xpc_connection_create_mach_service(g_service.c_str(),dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),0);if(!connection)throw std::runtime_error("connector_xpc_create_failed");xpc_connection_set_event_handler(connection,^(xpc_object_t){});xpc_connection_activate(connection);xpc_object_t message=xpc_dictionary_create(nullptr,nullptr,0);xpc_dictionary_set_data(message,"request",request.data(),request.size());dispatch_semaphore_t semaphore=dispatch_semaphore_create(0);__block xpc_object_t reply=nullptr;xpc_connection_send_message_with_reply(connection,message,dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^(xpc_object_t value){reply=value;dispatch_semaphore_signal(semaphore);});if(dispatch_semaphore_wait(semaphore,dispatch_time(DISPATCH_TIME_NOW,5*NSEC_PER_SEC))!=0){xpc_connection_cancel(connection);throw std::runtime_error("connector_xpc_timeout");}const void*bytes=nullptr;size_t n=0;if(xpc_get_type(reply)==XPC_TYPE_DICTIONARY)bytes=xpc_dictionary_get_data(reply,"response",&n);if(!bytes||n==0||n>g_max){xpc_connection_cancel(connection);throw std::runtime_error("connector_xpc_response_invalid");}std::string out(static_cast<const char*>(bytes),n);xpc_connection_cancel(connection);return out;}}
extern "C" {void* p1a_connector_alloc(intptr_t n){return n>0&&n<=64*1024*1024?std::malloc(static_cast<std::size_t>(n)):nullptr;}void p1a_connector_free(void*v){std::free(v);}uint32_t p1a_connector_abi_version(void){return 0x00020000u;}
int32_t p1a_connector_configure(const uint8_t*data,intptr_t size){std::lock_guard<std::mutex>l(g_mu);try{auto v=j::parse(std::string_view(reinterpret_cast<const char*>(data),static_cast<std::size_t>(size)));const auto&o=v.as_object();if(j::required_string(o,"schemaVersion")!="2.0.0")throw std::runtime_error("connector_config_schema_invalid");g_service=j::required_string(o,"address");auto n=j::required_int(o,"maxResponseBytes");if(g_service.empty()||n<65536||n>16*1024*1024)throw std::runtime_error("connector_config_invalid");g_max=static_cast<std::size_t>(n);g_response="{\"status\":\"configured\"}";return 0;}catch(const std::exception&e){set_error(e.what());return 1;}}
int32_t p1a_connector_request(const uint8_t*data,intptr_t size){std::lock_guard<std::mutex>l(g_mu);try{if(!data||size<=0||static_cast<std::size_t>(size)>g_max)throw std::runtime_error("connector_request_size_invalid");g_response=transact(std::string_view(reinterpret_cast<const char*>(data),static_cast<std::size_t>(size)));auto value=j::parse(g_response);return value.as_object().contains("status")&&j::required_string(value.as_object(),"status")=="denied"?2:0;}catch(const std::exception&e){set_error(e.what());return 1;}}
intptr_t p1a_connector_response_size(void){std::lock_guard<std::mutex>l(g_mu);return static_cast<intptr_t>(g_response.size());}intptr_t p1a_connector_copy_response(uint8_t*out,intptr_t cap){std::lock_guard<std::mutex>l(g_mu);if(!out||cap<0||static_cast<std::size_t>(cap)<g_response.size())return-1;std::memcpy(out,g_response.data(),g_response.size());return static_cast<intptr_t>(g_response.size());}void p1a_connector_close(void){std::lock_guard<std::mutex>l(g_mu);g_service.clear();g_response.clear();g_max=4*1024*1024;}}
