
#include "../common/p1a_connector.h"
#include "../../native/common/strict_json.hpp"
#include <windows.h>
#include <array>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <stdexcept>
#include <string>
#include <string_view>
namespace {namespace j=kristin::p1a::json;std::mutex g_mu;std::wstring g_pipe;std::string g_response;std::size_t g_max=4*1024*1024;
std::wstring widen(std::string_view s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),nullptr,0);if(n<=0)throw std::runtime_error("connector_utf8_invalid");std::wstring out(n,L'\0');MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),out.data(),n);return out;}
void set_error(std::string_view code){g_response=j::canonical(j::value(j::value::object{{"schemaVersion",j::value("2.0.0")},{"status",j::value("transport-error")},{"errorCode",j::value(std::string(code))}}));}
void write_all(HANDLE h,const void*data,DWORD size){auto*p=static_cast<const BYTE*>(data);while(size){DWORD n=0;if(!WriteFile(h,p,size,&n,nullptr)||n==0)throw std::runtime_error("connector_pipe_write_failed");p+=n;size-=n;}}
void read_all(HANDLE h,void*data,DWORD size){auto*p=static_cast<BYTE*>(data);while(size){DWORD n=0;if(!ReadFile(h,p,size,&n,nullptr)||n==0)throw std::runtime_error("connector_pipe_read_failed");p+=n;size-=n;}}
std::string transact(std::string_view request){if(g_pipe.empty())throw std::runtime_error("connector_not_configured");if(!WaitNamedPipeW(g_pipe.c_str(),5000))throw std::runtime_error("connector_pipe_unavailable");HANDLE h=CreateFileW(g_pipe.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)throw std::runtime_error("connector_pipe_access_denied");struct c{HANDLE h;~c(){if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);}}close{h};std::array<unsigned char,4>head{static_cast<unsigned char>(request.size()>>24),static_cast<unsigned char>(request.size()>>16),static_cast<unsigned char>(request.size()>>8),static_cast<unsigned char>(request.size())};write_all(h,head.data(),4);write_all(h,request.data(),static_cast<DWORD>(request.size()));read_all(h,head.data(),4);DWORD n=(DWORD(head[0])<<24)|(DWORD(head[1])<<16)|(DWORD(head[2])<<8)|head[3];if(n==0||n>g_max)throw std::runtime_error("connector_response_budget_exceeded");std::string out(n,'\0');read_all(h,out.data(),n);return out;}}
extern "C" {void* p1a_connector_alloc(intptr_t n){return n>0&&n<=64*1024*1024?std::malloc(static_cast<std::size_t>(n)):nullptr;}void p1a_connector_free(void*v){std::free(v);}uint32_t p1a_connector_abi_version(void){return 0x00020000u;}
int32_t p1a_connector_configure(const uint8_t*data,intptr_t size){std::lock_guard<std::mutex>l(g_mu);try{auto v=j::parse(std::string_view(reinterpret_cast<const char*>(data),static_cast<std::size_t>(size)));const auto&o=v.as_object();if(j::required_string(o,"schemaVersion")!="2.0.0")throw std::runtime_error("connector_config_schema_invalid");g_pipe=widen(j::required_string(o,"address"));auto n=j::required_int(o,"maxResponseBytes");if(g_pipe.empty()||n<65536||n>16*1024*1024)throw std::runtime_error("connector_config_invalid");g_max=static_cast<std::size_t>(n);g_response="{\"status\":\"configured\"}";return 0;}catch(const std::exception&e){set_error(e.what());return 1;}}
int32_t p1a_connector_request(const uint8_t*data,intptr_t size){std::lock_guard<std::mutex>l(g_mu);try{if(!data||size<=0||static_cast<std::size_t>(size)>g_max)throw std::runtime_error("connector_request_size_invalid");g_response=transact(std::string_view(reinterpret_cast<const char*>(data),static_cast<std::size_t>(size)));auto value=j::parse(g_response);return value.as_object().contains("status")&&j::required_string(value.as_object(),"status")=="denied"?2:0;}catch(const std::exception&e){set_error(e.what());return 1;}}
intptr_t p1a_connector_response_size(void){std::lock_guard<std::mutex>l(g_mu);return static_cast<intptr_t>(g_response.size());}intptr_t p1a_connector_copy_response(uint8_t*out,intptr_t cap){std::lock_guard<std::mutex>l(g_mu);if(!out||cap<0||static_cast<std::size_t>(cap)<g_response.size())return-1;std::memcpy(out,g_response.data(),g_response.size());return static_cast<intptr_t>(g_response.size());}void p1a_connector_close(void){std::lock_guard<std::mutex>l(g_mu);g_pipe.clear();g_response.clear();g_max=4*1024*1024;}}
