#!/usr/bin/env python3
"""Format only handwritten Dart source while preserving generator-owned files.

The repository intentionally commits some generated Dart contracts. Those files
must remain byte-for-byte owned by their Python generators so each generator's
``--check`` mode is stable. Running ``dart format`` on an entire directory can
rewrite the generated bytes and make the next generator check fail even though
both tools are individually correct.

This helper enumerates the handwritten formatting scope deterministically and
invokes ``dart format`` in bounded batches. It excludes generated directories,
common generated-Dart suffixes, build outputs, and tool state.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import subprocess
import sys
from typing import Iterable, Sequence

EXCLUDED_COMPONENTS = frozenset({
    ".dart_tool",
    ".git",
    ".idea",
    ".vscode",
    "build",
    "generated",
    "generated_plugin_registrant",
})
GENERATED_SUFFIXES = (
    ".g.dart",
    ".freezed.dart",
    ".gr.dart",
    ".mocks.dart",
    ".config.dart",
)
DEFAULT_ROOTS = ("lib", "test")
EXTRA_FILES = ("tool/prune_stale_legacy.dart",)
MAX_BATCH_FILES = 120
MAX_COMMAND_CHARS = 28000


class ScopeError(RuntimeError):
    """Expected formatting-scope failure."""


def is_generator_owned(relative: PurePosixPath) -> bool:
    lowered = tuple(part.casefold() for part in relative.parts)
    if any(part in EXCLUDED_COMPONENTS for part in lowered):
        return True
    name = relative.name.casefold()
    if name == "generated_plugin_registrant.dart":
        return True
    return any(name.endswith(suffix) for suffix in GENERATED_SUFFIXES)


def collect_dart_files(project: Path) -> list[str]:
    project = project.resolve()
    selected: set[str] = set()
    for root_name in DEFAULT_ROOTS:
        root = project / root_name
        if not root.is_dir():
            continue
        for path in root.rglob("*.dart"):
            if not path.is_file():
                continue
            relative = PurePosixPath(path.relative_to(project).as_posix())
            if is_generator_owned(relative):
                continue
            selected.add(relative.as_posix())
    for relative_text in EXTRA_FILES:
        path = project / relative_text
        relative = PurePosixPath(relative_text)
        if path.is_file() and not is_generator_owned(relative):
            selected.add(relative.as_posix())
    return sorted(selected)


def batched(values: Sequence[str]) -> Iterable[list[str]]:
    batch: list[str] = []
    length = 0
    for value in values:
        extra = len(value) + 3
        if batch and (len(batch) >= MAX_BATCH_FILES or length + extra > MAX_COMMAND_CHARS):
            yield batch
            batch = []
            length = 0
        batch.append(value)
        length += extra
    if batch:
        yield batch


def _print_canonical_sources(
    project: Path,
    dart: str,
    files: Sequence[str],
    formatter_output: str,
) -> None:
    selected = set(files)
    changed: list[str] = []
    for line in formatter_output.splitlines():
        if not line.startswith("Changed "):
            continue
        relative = line[len("Changed ") :].strip().replace("\\", "/")
        if relative in selected:
            changed.append(relative)
    for relative in changed:
        rendered = subprocess.run(
            [dart, "format", "--output=show", relative],
            cwd=project,
            env={**os.environ, "CI": "true"},
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
            check=False,
        )
        print(f"--- BEGIN CANONICAL DART: {relative} ---")
        if rendered.stdout:
            print(rendered.stdout, end="" if rendered.stdout.endswith("\n") else "\n")
        print(f"--- END CANONICAL DART: {relative} ---")


def run_format(project: Path, files: Sequence[str], *, check: bool) -> int:
    dart = shutil.which("dart")
    if dart is None:
        raise ScopeError("Dart SDK was not found on PATH")
    if not files:
        print("No handwritten Dart files were found in the formatting scope.")
        return 0

    prefix = [dart, "format"]
    if check:
        prefix.extend(["--output=none", "--set-exit-if-changed"])

    exit_code = 0
    for batch in batched(files):
        completed = subprocess.run(
            [*prefix, *batch],
            cwd=project,
            env={**os.environ, "CI": "true"},
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
            check=False,
        )
        if completed.stdout:
            print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n")
        if completed.returncode != 0:
            if check:
                _print_canonical_sources(project, dart, batch, completed.stdout)
            exit_code = completed.returncode
    return exit_code


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", default=".")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Apply canonical formatting to handwritten Dart files.")
    mode.add_argument("--check", action="store_true", help="Fail without writing when handwritten Dart formatting differs.")
    mode.add_argument("--list-json", action="store_true", help="Print the deterministic handwritten scope without invoking Dart.")
    args = parser.parse_args()

    project = Path(args.project).expanduser().resolve()
    if not project.is_dir():
        raise ScopeError(f"project directory does not exist: {project}")
    files = collect_dart_files(project)
    if args.list_json:
        print(json.dumps({"count": len(files), "files": files}, indent=2, sort_keys=True))
        return 0
    return run_format(project, files, check=args.check)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ScopeError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(2)
