#!/usr/bin/env python3
"""Generate deterministic Dart constants for v1.6/v1.7 contracts."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

from dart_string_literal import dart_single_quoted_string

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = (
    "project_profile.v2.json",
    "project_manager_snapshot.v1.json",
    "model_routing_policy.v1.json",
    "execution_progress.v1.json",
    "verification_report.v1.json",
    "convergence_decision.v1.json",
)
OUTPUT = ROOT / "lib" / "product" / "generated" / "v170_contracts.g.dart"


def canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def render() -> str:
    values = {name: json.loads((ROOT / "schemas" / name).read_text(encoding="utf-8")) for name in SCHEMAS}
    digest = hashlib.sha256(canonical(values).encode("utf-8")).hexdigest()
    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        "// Generated by tool/generate_v170_contracts.py.",
        "",
        f"const String v170ContractsSha256 = '{digest}';",
        "",
        "const Map<String, Object?> v170ContractSchemas = <String, Object?>{",
    ]
    for name in SCHEMAS:
        encoded = json.dumps(values[name], sort_keys=True, ensure_ascii=False)
        escaped = dart_single_quoted_string(encoded)
        lines.append(f"  '{name}': '{escaped}',")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"FAIL {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"PASS {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
