#!/usr/bin/env python3
"""Generate deterministic Dart constants for v1.8 schemas."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = (
    'knowledge_object_manifest.v1.json',
    'memory_admission_policy.v1.json',
    'skill_candidate.v1.json',
    'published_skill.v1.json',
    'file_adapter_registry.v1.json',
    'research_freshness_policy.v1.json',
)
OUTPUT = ROOT / 'lib' / 'product' / 'generated' / 'v180_contracts.g.dart'


def canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False)


def render() -> str:
    values = {name: json.loads((ROOT / 'schemas' / name).read_text(encoding='utf-8')) for name in SCHEMAS}
    digest = hashlib.sha256(canonical(values).encode('utf-8')).hexdigest()
    lines = [
        '// GENERATED FILE — DO NOT EDIT.',
        '// Generated by tool/generate_v180_contracts.py.',
        '',
        f"const String v180ContractsSha256 = '{digest}';",
        '',
        'const Map<String, String> v180ContractSchemas = <String, String>{',
    ]
    for name in SCHEMAS:
        encoded = json.dumps(values[name], sort_keys=True, ensure_ascii=False)
        escaped = encoded.replace('\\', '\\\\').replace("'", "\\'")
        lines.append(f"  '{name}': '{escaped}',")
    lines.extend(['};', ''])
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != content:
            print(f'FAIL {OUTPUT.relative_to(ROOT)}')
            return 1
        print(f'PASS {OUTPUT.relative_to(ROOT)}')
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding='utf-8')
    print(OUTPUT)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
