#!/usr/bin/env python3
"""Generate deterministic Dart constants for v1.9 interoperability contracts."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = (
    "capability_manifest.v1.json",
    "signed_capability_manifest.v1.json",
    "policy_profile.v1.json",
    "fleet_profile.v1.json",
    "mcp_server_manifest.v1.json",
    "a2a_task_contract.v1.json",
    "support_compatibility_policy.v1.json",
    "update_channel_manifest.v1.json",
    "audit_chain_entry.v1.json",
)
OUTPUT = ROOT / "lib" / "product" / "generated" / "v190_contracts.g.dart"


def canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def render() -> str:
    values = {name: json.loads((ROOT / "schemas" / name).read_text(encoding="utf-8")) for name in SCHEMAS}
    digest = hashlib.sha256(canonical(values).encode("utf-8")).hexdigest()
    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        "// Generated by tool/generate_v190_contracts.py.",
        "",
        f"const String v190ContractsSha256 = '{digest}';",
        "",
        "const Map<String, Object?> v190ContractSchemas = <String, Object?>{",
    ]
    for name in SCHEMAS:
        encoded = json.dumps(values[name], sort_keys=True, ensure_ascii=False)
        escaped = encoded.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
        lines.append(f"  '{name}': '{escaped}',")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"FAIL {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"PASS {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
