#!/usr/bin/env python3
"""Semantic regression tests for Worker E native parity readiness contracts."""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "tool" / "worker_e_native_parity_readiness.py"
SPEC = importlib.util.spec_from_file_location("worker_e_native_parity_readiness", MODULE_PATH)
assert SPEC and SPEC.loader
readiness = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = readiness
SPEC.loader.exec_module(readiness)

class WorkerENativeParityReadinessTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="worker-e-readiness-")
        self.project = Path(self.temp.name)
        referenced: set[Path] = set(readiness.WORKER_E_DURABLE_PATHS)
        referenced.add(Path("SOURCE_MANIFEST.sha256"))
        for key in ("dependency", "inventory", "matrix", "fixtures", "isolation", "devices", "manifest", "registry"):
            referenced.add(readiness.FILES[key])
        for relative in list(referenced):
            source = ROOT / relative
            if source.is_file():
                target = self.project / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, target)
        # Copy every source/evidence path referenced by the readiness records.
        dependency = json.loads(
            (self.project / readiness.FILES["dependency"]).read_text(encoding="utf-8")
        )
        isolation = json.loads(
            (self.project / readiness.FILES["isolation"]).read_text(encoding="utf-8")
        )
        inventory = readiness._load_inventory(self.project)
        for rows in (
            dependency.get("dependencies", []),
            inventory.get("capabilities", []),
            isolation.get("tiers", []),
        ):
            for row in rows:
                for field in ("evidencePaths", "implementationPaths", "testPaths"):
                    for raw in row.get(field, []):
                        source = ROOT / raw
                        target = self.project / raw
                        target.parent.mkdir(parents=True, exist_ok=True)
                        if source.is_file():
                            shutil.copy2(source, target)
                        else:
                            target.write_text("fixture source placeholder\n", encoding="utf-8")
        # Rebuild a minimal manifest for the copied source set.  The production
        # path is generated by tool/p1a_refresh_source_manifest.py.
        lines = []
        for relative in sorted(readiness.WORKER_E_DURABLE_PATHS, key=lambda item: item.as_posix()):
            path = self.project / relative
            lines.append(f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {relative.as_posix()}")
        (self.project / "SOURCE_MANIFEST.sha256").write_text("\n".join(lines) + "\n", encoding="utf-8")

    def tearDown(self) -> None:
        self.temp.cleanup()

    def load(self, key: str) -> dict:
        if key == "inventory":
            return readiness._load_inventory(self.project)
        if key == "matrix":
            return readiness._load_matrix(self.project)
        if key == "fixtures":
            return readiness._load_fixtures(self.project)
        if key == "isolation":
            return readiness._load_isolation(self.project)
        return json.loads((self.project / readiness.FILES[key]).read_text(encoding="utf-8"))

    def save(self, key: str, value: dict) -> None:
        if key == "inventory":
            index = json.loads(
                (self.project / readiness.FILES["inventory"]).read_text(encoding="utf-8")
            )
            for platform in ("windows", "macos", "linux"):
                rows = [row for row in value["capabilities"] if row["platform"] == platform]
                refs = [ref for ref in index["catalogFiles"] if ref["platform"] == platform]
                cursor = 0
                for position, ref in enumerate(refs):
                    take = ref["count"] if position < len(refs) - 1 else len(rows) - cursor
                    selected = rows[cursor : cursor + take]
                    cursor += take
                    path = self.project / ref["path"]
                    fragment = json.loads(path.read_text(encoding="utf-8"))
                    fragment["capabilities"] = selected
                    ref["count"] = len(selected)
                    path.write_text(
                        json.dumps(fragment, indent=2, sort_keys=True) + "\n",
                        encoding="utf-8",
                    )
            index["capabilityCount"] = len(value["capabilities"])
            (self.project / readiness.FILES["inventory"]).write_text(
                json.dumps(index, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            return
        if key == "matrix":
            index = json.loads(
                (self.project / readiness.FILES["matrix"]).read_text(encoding="utf-8")
            )
            for ref in index["catalogFiles"]:
                path = self.project / ref["path"]
                fragment = json.loads(path.read_text(encoding="utf-8"))
                names = {row["operation"] for row in fragment["operations"]}
                selected = [
                    row for row in value["operations"] if row["operation"] in names
                ]
                fragment["operations"] = selected
                ref["count"] = len(selected)
                path.write_text(
                    json.dumps(fragment, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8",
                )
            index.update(
                {
                    key_name: value[key_name]
                    for key_name in (
                        "fallbackContract",
                        "behavioralParityClaimed",
                        "claimBoundary",
                    )
                    if key_name in value
                }
            )
            (self.project / readiness.FILES["matrix"]).write_text(
                json.dumps(index, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            return
        if key == "fixtures":
            index = json.loads(
                (self.project / readiness.FILES["fixtures"]).read_text(encoding="utf-8")
            )
            cursor = 0
            for position, ref in enumerate(index["catalogFiles"]):
                take = ref["count"] if position < len(index["catalogFiles"]) - 1 else len(value["fixtures"]) - cursor
                selected = value["fixtures"][cursor : cursor + take]
                cursor += take
                path = self.project / ref["path"]
                fragment = json.loads(path.read_text(encoding="utf-8"))
                fragment["fixtures"] = selected
                ref["count"] = len(selected)
                path.write_text(
                    json.dumps(fragment, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8",
                )
            (self.project / readiness.FILES["fixtures"]).write_text(
                json.dumps(index, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            return
        if key == "isolation":
            index = json.loads(
                (self.project / readiness.FILES["isolation"]).read_text(encoding="utf-8")
            )
            for ref in index["catalogFiles"]:
                selected = [
                    row for row in value["tiers"] if row["platform"] == ref["platform"]
                ]
                path = self.project / ref["path"]
                fragment = json.loads(path.read_text(encoding="utf-8"))
                fragment["tiers"] = selected
                ref["count"] = len(selected)
                path.write_text(
                    json.dumps(fragment, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8",
                )
            (self.project / readiness.FILES["isolation"]).write_text(
                json.dumps(index, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            return
        (self.project / readiness.FILES[key]).write_text(
            json.dumps(value, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def test_full_check_passes_and_is_non_mutating(self) -> None:
        before = readiness._snapshot(self.project)
        report = readiness.check(self.project)
        after = readiness._snapshot(self.project)
        self.assertEqual("PASS", report["resultState"])
        self.assertEqual([], report["mutatedPaths"])
        self.assertEqual(before, after)
        self.assertEqual("NOT_EVALUATED", report["certification"])
        self.assertEqual(
            {"windows": "BLOCKED", "macos": "BLOCKED", "linux": "BLOCKED"},
            report["platformBehavior"],
        )

    def test_duplicate_capability_identity_is_rejected(self) -> None:
        data = self.load("inventory")
        data["capabilities"].append(copy.deepcopy(data["capabilities"][0]))
        self.save("inventory", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "duplicate capability IDs"):
            readiness.check_inventory(self.project)

    def test_source_presence_cannot_promote_behavior_support(self) -> None:
        data = self.load("inventory")
        data["capabilities"][0]["behavioralEvidenceClassification"] = "IMPLEMENTED"
        data["capabilities"][0]["supportClassification"] = "PLATFORM_SUPPORTED"
        self.save("inventory", data)
        with self.assertRaises(readiness.ReadinessError):
            readiness.check_inventory(self.project)

    def test_platform_omission_is_rejected(self) -> None:
        data = self.load("matrix")
        del data["operations"][0]["platformSpecificDetails"]["macos"]
        self.save("matrix", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "platform omission"):
            readiness.check_platform_matrix(self.project)

    def test_silent_fallback_is_rejected(self) -> None:
        data = self.load("matrix")
        data["fallbackContract"]["silentFallbackAllowed"] = True
        self.save("matrix", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "silent fallback"):
            readiness.check_no_silent_fallback(self.project)

    def test_missing_forbidden_fallback_vector_is_rejected(self) -> None:
        data = self.load("matrix")
        data["fallbackContract"]["forbiddenSilentDegradations"].remove(
            "unknown process identity"
        )
        self.save("matrix", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "degradation list"):
            readiness.check_no_silent_fallback(self.project)

    def test_fixture_real_elevation_is_rejected(self) -> None:
        data = self.load("fixtures")
        data["fixtures"][0]["privilegePolicy"] = "REAL_ELEVATION_ALLOWED"
        self.save("fixtures", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "real elevation"):
            readiness.check_fixtures(self.project)

    def test_fixture_behavioral_pass_is_rejected(self) -> None:
        data = self.load("fixtures")
        data["fixtures"][0]["behavioralPassClaimed"] = True
        data["fixtures"][0]["behavioralExecution"]["linux"] = "PASS"
        self.save("fixtures", data)
        with self.assertRaises(readiness.ReadinessError):
            readiness.check_fixtures(self.project)

    def test_isolation_source_marker_cannot_be_advertised(self) -> None:
        data = self.load("isolation")
        data["tiers"][0]["advertisedTier"] = "HIGH"
        self.save("isolation", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "advertised without proof"):
            readiness.check_isolation(self.project)

    def test_real_device_access_and_completion_claims_are_rejected(self) -> None:
        data = self.load("devices")
        data["ordinaryCi"]["cameraCapture"] = True
        data["claims"]["p11_009Complete"] = True
        self.save("devices", data)
        with self.assertRaises(readiness.ReadinessError):
            readiness.check_devices(self.project)

    def test_p2_004_dependency_cannot_be_promoted_without_measurements(self) -> None:
        data = self.load("dependency")
        p2 = next(row for row in data["dependencies"] if row["taskId"] == "P2-004")
        p2["decision"] = "READY"
        data["activationDecision"]["p11_001AdrPreparationAuthorized"] = True
        self.save("dependency", data)
        with self.assertRaises(readiness.ReadinessError):
            readiness.check_dependency_status(self.project)

    def test_test_center_profiles_are_non_mutating_and_structured(self) -> None:
        readiness.check_test_center(self.project)
        data = self.load("registry")
        profile = next(
            row
            for row in data["projectTestProfiles"]
            if row["stableCheckId"] == "tc.p11.readiness.dependency-status"
        )
        profile["argv"] = ["bash", "-lc", "python tool/worker_e_native_parity_readiness.py --check"]
        self.save("registry", data)
        with self.assertRaisesRegex(readiness.ReadinessError, "structured bounded argv"):
            readiness.check_test_center(self.project)

    def test_affected_test_selection_is_order_independent(self) -> None:
        data = self.load("registry")
        mappings = [
            row
            for row in data["affectedTestMappings"]
            if row["mappingId"].startswith("affected.p11-readiness")
        ]
        paths = [
            "release/evidence/P11-001/platform-gap-matrix.json",
            "tool/worker_e_native_parity_readiness.py",
            "authority_service/native/windows/authority_service_windows.cpp",
        ]
        forward = readiness._select_affected(paths, mappings)
        reverse = readiness._select_affected(reversed(paths), reversed(mappings))
        self.assertEqual(forward, reverse)
        self.assertIn("tc.p11.readiness.no-silent-fallback", forward)

    def test_source_manifest_binding_is_required(self) -> None:
        path = self.project / readiness.FILES["devices"]
        path.write_text(path.read_text(encoding="utf-8") + " ", encoding="utf-8")
        with self.assertRaisesRegex(readiness.ReadinessError, "source manifest mismatch"):
            readiness.check_source_manifest(self.project)

    def test_unknown_stable_test_id_is_rejected(self) -> None:
        with self.assertRaisesRegex(readiness.ReadinessError, "unknown stable test ID"):
            readiness._run_selected(self.project, "tc.p11.readiness.unknown")


if __name__ == "__main__":
    unittest.main()
