#include "authority_core_v2.hpp"

#include <windows.h>
#include <aclapi.h>
#include <bcrypt.h>
#include <ncrypt.h>
#include <ntsecapi.h>
#include <sddl.h>
#include <softpub.h>
#include <wincrypt.h>
#include <wintrust.h>

#include <array>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#pragma comment(lib,"advapi32.lib")
#pragma comment(lib,"bcrypt.lib")
#pragma comment(lib,"crypt32.lib")
#pragma comment(lib,"ncrypt.lib")
#pragma comment(lib,"wintrust.lib")
namespace kp=kristin::p1a;
namespace {
DWORD checked_dword(std::size_t value,const char*error){if(value>static_cast<std::size_t>((std::numeric_limits<DWORD>::max)()))throw std::runtime_error(error);return static_cast<DWORD>(value);}
ULONG checked_ulong(std::size_t value,const char*error){if(value>static_cast<std::size_t>((std::numeric_limits<ULONG>::max)()))throw std::runtime_error(error);return static_cast<ULONG>(value);}
USHORT checked_ushort_bytes(std::size_t characters,const char*error){if(characters>static_cast<std::size_t>((std::numeric_limits<USHORT>::max)())/sizeof(wchar_t))throw std::runtime_error(error);return static_cast<USHORT>(characters*sizeof(wchar_t));}
int checked_int(std::size_t value,const char*error){if(value>static_cast<std::size_t>((std::numeric_limits<int>::max)()))throw std::runtime_error(error);return static_cast<int>(value);}
SERVICE_STATUS_HANDLE g_status_handle=nullptr;SERVICE_STATUS g_status{};HANDLE g_stop_event=nullptr;std::filesystem::path g_service_config;
struct win_handle{HANDLE h=INVALID_HANDLE_VALUE;win_handle()=default;explicit win_handle(HANDLE v):h(v){}~win_handle(){if(h&&h!=INVALID_HANDLE_VALUE)CloseHandle(h);}win_handle(const win_handle&)=delete;win_handle&operator=(const win_handle&)=delete;};
struct ncrypt_handle{NCRYPT_HANDLE h=0;~ncrypt_handle(){if(h)NCryptFreeObject(h);}};
std::wstring widen(std::string_view s){if(s.empty())return{};const int source_size=checked_int(s.size(),"utf8_too_large");const int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),source_size,nullptr,0);if(n<=0)throw std::runtime_error("utf8_invalid");std::wstring w(static_cast<std::size_t>(n),L'\0');if(MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),source_size,w.data(),n)!=n)throw std::runtime_error("utf8_conversion_failed");return w;}
std::string narrow(std::wstring_view w){if(w.empty())return{};const int source_size=checked_int(w.size(),"utf16_too_large");const int n=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,w.data(),source_size,nullptr,0,nullptr,nullptr);if(n<=0)throw std::runtime_error("utf16_invalid");std::string s(static_cast<std::size_t>(n),'\0');if(WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,w.data(),source_size,s.data(),n,nullptr,nullptr)!=n)throw std::runtime_error("utf16_conversion_failed");return s;}
std::string base64(const unsigned char*p,std::size_t n){const DWORD input_size=checked_dword(n,"base64_input_too_large");DWORD out=0;if(!CryptBinaryToStringA(p,input_size,CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,nullptr,&out))throw std::runtime_error("base64_size_failed");std::string s(static_cast<std::size_t>(out),'\0');if(!CryptBinaryToStringA(p,input_size,CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,s.data(),&out))throw std::runtime_error("base64_failed");if(!s.empty()&&s.back()=='\0')s.pop_back();return s;}
std::vector<unsigned char> unhex(std::wstring_view h){if(h.size()<32||h.size()%2)throw std::runtime_error("lsa_secret_invalid");std::vector<unsigned char>out(h.size()/2);for(std::size_t i=0;i<out.size();++i){auto cv=[](wchar_t c)->int{if(c>=L'0'&&c<=L'9')return c-L'0';if(c>=L'a'&&c<=L'f')return 10+c-L'a';if(c>=L'A'&&c<=L'F')return 10+c-L'A';return-1;};int a=cv(h[i*2]),b=cv(h[i*2+1]);if(a<0||b<0)throw std::runtime_error("lsa_secret_hex_invalid");out[i]=static_cast<unsigned char>((a<<4)|b);}return out;}
std::vector<unsigned char> lsa_secret(const std::wstring&name){LSA_OBJECT_ATTRIBUTES oa{};oa.Length=static_cast<ULONG>(sizeof(oa));LSA_HANDLE policy=nullptr;if(LsaOpenPolicy(nullptr,&oa,POLICY_GET_PRIVATE_INFORMATION,&policy)!=0)throw std::runtime_error("lsa_open_failed");const USHORT key_bytes=checked_ushort_bytes(name.size(),"lsa_secret_name_too_large");LSA_UNICODE_STRING key{key_bytes,key_bytes,const_cast<PWSTR>(name.data())};PLSA_UNICODE_STRING value=nullptr;const NTSTATUS st=LsaRetrievePrivateData(policy,&key,&value);LsaClose(policy);if(st!=0||!value)throw std::runtime_error("lsa_secret_missing");std::wstring secret(value->Buffer,static_cast<std::size_t>(value->Length/sizeof(wchar_t)));LsaFreeMemory(value);return unhex(secret);}
void lsa_store(const std::wstring&name,const std::wstring&hex){LSA_OBJECT_ATTRIBUTES oa{};oa.Length=static_cast<ULONG>(sizeof(oa));LSA_HANDLE policy=nullptr;if(LsaOpenPolicy(nullptr,&oa,POLICY_CREATE_SECRET,&policy)!=0)throw std::runtime_error("lsa_open_write_failed");const USHORT key_bytes=checked_ushort_bytes(name.size(),"lsa_secret_name_too_large");const USHORT value_bytes=checked_ushort_bytes(hex.size(),"lsa_secret_value_too_large");LSA_UNICODE_STRING key{key_bytes,key_bytes,const_cast<PWSTR>(name.data())};LSA_UNICODE_STRING value{value_bytes,value_bytes,const_cast<PWSTR>(hex.data())};const NTSTATUS st=LsaStorePrivateData(policy,&key,&value);LsaClose(policy);if(st!=0)throw std::runtime_error("lsa_store_failed");}
std::wstring read_secret_hex_stdin(){std::wstring value;if(!std::getline(std::wcin,value))throw std::runtime_error("secret_stdin_read_failed");while(!value.empty()&&(value.back()==L'\r'||value.back()==L'\n'))value.pop_back();(void)unhex(value);return value;}
std::string file_sha256(const std::filesystem::path&p){std::ifstream in(p,std::ios::binary);if(!in)throw std::runtime_error("file_hash_open_failed");kp::sha256_state h;std::array<char,65536>b{};while(in){in.read(b.data(),static_cast<std::streamsize>(b.size()));auto n=in.gcount();if(n>0)h.update(b.data(),static_cast<std::size_t>(n));}auto d=h.finish();return kp::hex_bytes(d.data(),d.size());}
std::wstring process_image(DWORD pid){win_handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid));if(!process.h)throw std::runtime_error("peer_process_open_failed");std::wstring path(32768,L'\0');DWORD n=static_cast<DWORD>(path.size());if(!QueryFullProcessImageNameW(process.h,0,path.data(),&n))throw std::runtime_error("peer_image_unavailable");path.resize(n);return path;}
std::wstring token_sid(HANDLE token){DWORD n=0;GetTokenInformation(token,TokenUser,nullptr,0,&n);std::vector<unsigned char>b(n);if(!GetTokenInformation(token,TokenUser,b.data(),n,&n))throw std::runtime_error("token_user_failed");auto*tu=reinterpret_cast<TOKEN_USER*>(b.data());LPWSTR sid=nullptr;if(!ConvertSidToStringSidW(tu->User.Sid,&sid))throw std::runtime_error("sid_string_failed");std::wstring out(sid);LocalFree(sid);return out;}
bool token_is_appcontainer(HANDLE token){DWORD v=0,n=0;return GetTokenInformation(token,TokenIsAppContainer,&v,static_cast<DWORD>(sizeof(v)),&n)&&v!=0;}
bool verify_authenticode(const std::wstring&path){WINTRUST_FILE_INFO file{};file.cbStruct=static_cast<DWORD>(sizeof(file));file.pcwszFilePath=path.c_str();WINTRUST_DATA data{};data.cbStruct=static_cast<DWORD>(sizeof(data));data.dwUIChoice=WTD_UI_NONE;data.fdwRevocationChecks=WTD_REVOKE_WHOLECHAIN;data.dwUnionChoice=WTD_CHOICE_FILE;data.pFile=&file;data.dwStateAction=WTD_STATEACTION_VERIFY;GUID action=WINTRUST_ACTION_GENERIC_VERIFY_V2;LONG result=WinVerifyTrust(nullptr,&action,&data);data.dwStateAction=WTD_STATEACTION_CLOSE;WinVerifyTrust(nullptr,&action,&data);return result==ERROR_SUCCESS;}
std::string signer_certificate_sha256(const std::wstring&path){DWORD encoding=0,content=0,format=0;HCERTSTORE store=nullptr;HCRYPTMSG message=nullptr;const void*context=nullptr;if(!CryptQueryObject(CERT_QUERY_OBJECT_FILE,path.c_str(),CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED|CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED,CERT_QUERY_FORMAT_FLAG_BINARY,0,&encoding,&content,&format,&store,&message,&context))throw std::runtime_error("desktop_signer_query_failed");auto cleanup=[&](){if(message)CryptMsgClose(message);if(store)CertCloseStore(store,0);};DWORD size=0;if(!CryptMsgGetParam(message,CMSG_SIGNER_INFO_PARAM,0,nullptr,&size)||size==0){cleanup();throw std::runtime_error("desktop_signer_info_missing");}std::vector<unsigned char>buffer(size);if(!CryptMsgGetParam(message,CMSG_SIGNER_INFO_PARAM,0,buffer.data(),&size)){cleanup();throw std::runtime_error("desktop_signer_info_failed");}auto*signer=reinterpret_cast<PCMSG_SIGNER_INFO>(buffer.data());CERT_INFO info{};info.Issuer=signer->Issuer;info.SerialNumber=signer->SerialNumber;PCCERT_CONTEXT cert=CertFindCertificateInStore(store,X509_ASN_ENCODING|PKCS_7_ASN_ENCODING,0,CERT_FIND_SUBJECT_CERT,&info,nullptr);if(!cert){cleanup();throw std::runtime_error("desktop_signer_certificate_missing");}std::array<unsigned char,32>digest{};DWORD digest_size=static_cast<DWORD>(digest.size());const BOOL ok=CryptHashCertificate2(BCRYPT_SHA256_ALGORITHM,0,nullptr,cert->pbCertEncoded,cert->cbCertEncoded,digest.data(),&digest_size);CertFreeCertificateContext(cert);cleanup();if(!ok||static_cast<std::size_t>(digest_size)!=digest.size())throw std::runtime_error("desktop_signer_certificate_hash_failed");return kp::hex_bytes(digest.data(),digest.size());}

struct config final{std::wstring pipe,desktop_sid,worker_sid,key_name,grant_secret,owner_secret;std::filesystem::path policy,state,audit,revocations,approvals;std::string desktop_hash,desktop_publisher_sha256,service_instance;};
config load_config(const std::filesystem::path&p){auto v=kp::json::parse(kp::read_text_file(p));const auto&o=v.as_object();config c;c.pipe=widen(kp::json::required_string(o,"pipeName"));c.desktop_sid=widen(kp::json::required_string(o,"desktopSid"));c.worker_sid=widen(kp::json::required_string(o,"workerAppContainerSid"));c.key_name=widen(kp::json::required_string(o,"cngKeyName"));c.grant_secret=widen(kp::json::required_string(o,"grantLsaSecretName"));c.owner_secret=widen(kp::json::required_string(o,"ownerLsaSecretName"));c.policy=widen(kp::json::required_string(o,"policySnapshotPath"));c.state=widen(kp::json::required_string(o,"statePath"));c.audit=widen(kp::json::required_string(o,"auditPath"));c.revocations=widen(kp::json::required_string(o,"revocationsPath"));c.approvals=widen(kp::json::required_string(o,"approvalsPath"));c.desktop_hash=kp::json::required_string(o,"desktopExecutableSha256");c.desktop_publisher_sha256=kp::json::required_string(o,"desktopPublisherCertificateSha256");c.service_instance=kp::json::required_string(o,"serviceInstanceId");return c;}

class win_crypto final:public kp::crypto_backend{public:win_crypto(const config&c):key_name_(c.key_name),grant_(lsa_secret(c.grant_secret)),owner_(lsa_secret(c.owner_secret)){if(NCryptOpenStorageProvider(&provider_.h,MS_PLATFORM_CRYPTO_PROVIDER,0)!=ERROR_SUCCESS)throw std::runtime_error("platform_ksp_required");if(NCryptOpenKey(provider_.h,&key_.h,key_name_.c_str(),0,NCRYPT_MACHINE_KEY_FLAG)!=ERROR_SUCCESS)throw std::runtime_error("provisioned_cng_key_missing");DWORD policy=0,n=0;if(NCryptGetProperty(key_.h,NCRYPT_EXPORT_POLICY_PROPERTY,reinterpret_cast<PBYTE>(&policy),static_cast<DWORD>(sizeof(policy)),&n,0)!=ERROR_SUCCESS||policy!=0)throw std::runtime_error("cng_key_export_policy_invalid");DWORD blob_size=0;if(NCryptExportKey(key_.h,0,BCRYPT_ECCPUBLIC_BLOB,nullptr,nullptr,0,&blob_size,0)!=ERROR_SUCCESS)throw std::runtime_error("cng_public_export_failed");std::vector<unsigned char>blob(blob_size);if(NCryptExportKey(key_.h,0,BCRYPT_ECCPUBLIC_BLOB,nullptr,blob.data(),blob_size,&blob_size,0)!=ERROR_SUCCESS||blob_size<8+64)throw std::runtime_error("cng_public_export_failed");std::vector<unsigned char>spki={0x30,0x59,0x30,0x13,0x06,0x07,0x2a,0x86,0x48,0xce,0x3d,0x02,0x01,0x06,0x08,0x2a,0x86,0x48,0xce,0x3d,0x03,0x01,0x07,0x03,0x42,0x00,0x04};spki.insert(spki.end(),blob.begin()+8,blob.begin()+8+64);public_=base64(spki.data(),spki.size());attestation_=kp::sha256_hex(narrow(key_name_)+"|"+public_+"|platform-ksp|export-policy-zero");DWORD private_size=0;auto private_status=NCryptExportKey(key_.h,0,NCRYPT_PKCS8_PRIVATE_KEY_BLOB,nullptr,nullptr,0,&private_size,0);export_denied_=private_status!=ERROR_SUCCESS;if(!export_denied_)throw std::runtime_error("cng_private_export_not_denied");}
 ~win_crypto()override{SecureZeroMemory(grant_.data(),grant_.size());SecureZeroMemory(owner_.data(),owner_.size());}
 std::string hmac_sha256_hex(std::string_view purpose,std::string_view key_id,std::string_view message)override{if(!kp::valid_identifier(key_id))throw std::runtime_error("hmac_key_id_invalid");const auto&secret=kp::hmac_secret_for_purpose(purpose)==kp::hmac_secret_kind::owner_approval?owner_:grant_;BCRYPT_ALG_HANDLE alg=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;if(BCryptOpenAlgorithmProvider(&alg,BCRYPT_SHA256_ALGORITHM,nullptr,BCRYPT_ALG_HANDLE_HMAC_FLAG)!=0)throw std::runtime_error("bcrypt_hmac_open_failed");DWORD object_size=0,n=0;BCryptGetProperty(alg,BCRYPT_OBJECT_LENGTH,reinterpret_cast<PUCHAR>(&object_size),static_cast<ULONG>(sizeof(object_size)),&n,0);std::vector<unsigned char>object(object_size);std::array<unsigned char,32>out{};bool ok=BCryptCreateHash(alg,&hash,object.data(),object_size,const_cast<PUCHAR>(secret.data()),checked_ulong(secret.size(),"bcrypt_secret_too_large"),0)==0&&BCryptHashData(hash,reinterpret_cast<PUCHAR>(const_cast<char*>(purpose.data())),checked_ulong(purpose.size(),"bcrypt_purpose_too_large"),0)==0&&BCryptHashData(hash,reinterpret_cast<PUCHAR>(const_cast<char*>(message.data())),checked_ulong(message.size(),"bcrypt_message_too_large"),0)==0&&BCryptFinishHash(hash,out.data(),checked_ulong(out.size(),"bcrypt_digest_too_large"),0)==0;if(hash)BCryptDestroyHash(hash);if(alg)BCryptCloseAlgorithmProvider(alg,0);if(!ok)throw std::runtime_error("bcrypt_hmac_failed");return kp::hex_bytes(out.data(),out.size());}
 kp::signature_result sign_effect_permit(std::string_view canonical)override{kp::sha256_state h;h.update(canonical);auto digest=h.finish();DWORD size=0;if(NCryptSignHash(key_.h,nullptr,digest.data(),checked_dword(digest.size(),"cng_digest_too_large"),nullptr,0,&size,0)!=ERROR_SUCCESS)throw std::runtime_error("cng_sign_size_failed");std::vector<unsigned char>sig(size);if(NCryptSignHash(key_.h,nullptr,digest.data(),checked_dword(digest.size(),"cng_digest_too_large"),sig.data(),size,&size,0)!=ERROR_SUCCESS)throw std::runtime_error("cng_sign_failed");sig.resize(size);return{"ecdsa-p256-sha256","p1a-permit-windows",base64(sig.data(),sig.size()),public_,"windows-platform-ksp",attestation_,true,export_denied_};}
 kp::json::value public_description()const override{return kp::json::value(kp::json::value::object{{"algorithm",kp::json::value("ecdsa-p256-sha256")},{"keyId",kp::json::value("p1a-permit-windows")},{"publicKeySpkiBase64",kp::json::value(public_)},{"provider",kp::json::value("windows-platform-ksp")},{"providerAttestationSha256",kp::json::value(attestation_)},{"nonExportable",kp::json::value(true)},{"privateExportDenied",kp::json::value(export_denied_)}});}
 private:std::wstring key_name_;ncrypt_handle provider_,key_;std::vector<unsigned char>grant_,owner_;std::string public_,attestation_;bool export_denied_=false;};

class win_state final:public kp::state_backend{public:win_state(std::filesystem::path state,std::filesystem::path audit,std::filesystem::path rev,std::filesystem::path approvals):state_(std::move(state)),audit_(std::move(audit)),rev_(std::move(rev)),approvals_(std::move(approvals)){std::filesystem::create_directories(state_.parent_path());file_.h=CreateFileW(state_.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_HIDDEN|FILE_ATTRIBUTE_NOT_CONTENT_INDEXED,nullptr);if(file_.h==INVALID_HANDLE_VALUE)throw std::runtime_error("state_exclusive_open_failed");load();++generation_;append("GENERATION\t"+std::to_string(generation_));}
 std::uint64_t revocation_epoch()const override{load_rev();return epoch_;}bool capability_revoked(std::string_view id)const override{load_rev();return revoked_.contains(std::string(id));}bool nonce_consumed(std::string_view n)const override{return nonces_.contains(std::string(n));}std::uint64_t grant_use_count(std::string_view id)const override{auto i=uses_.find(std::string(id));return i==uses_.end()?0:i->second;}std::string audit_head_sha256()const override{return audit_head_;}bool permit_exists(std::string_view id)const override{return permits_.contains(std::string(id));}
 kp::json::value owner_approval(std::string_view id)const override{if(auto it=persisted_approvals_.find(std::string(id));it!=persisted_approvals_.end())return kp::json::parse(it->second);auto v=kp::json::parse(kp::read_text_file(approvals_));const auto&o=v.as_object();for(const auto&row:kp::json::required_array(o,"approvals")){const auto&r=row.as_object();if(kp::json::required_string(r,"approvalId")==id)return row;}throw std::runtime_error("owner_approval_missing");}
 void commit_owner_approval(std::string_view id,std::string_view canonical)override{if(persisted_approvals_.contains(std::string(id)))throw std::runtime_error("owner_approval_replay");append("APPROVAL\t"+std::string(id)+"\t"+std::string(canonical));persisted_approvals_[std::string(id)]=std::string(canonical);}
 void commit_authorization(std::string_view nonce,std::string_view grant,std::uint64_t use,std::string_view permit,std::string_view audit,std::string_view digest)override{append("USE\t"+std::string(grant)+"\t"+std::to_string(use)+"\t"+std::string(nonce));append("PERMIT\t"+std::string(permit));append_audit(audit);append("AUDIT\t"+std::string(digest));nonces_.insert(std::string(nonce));uses_[std::string(grant)]=use;permits_.insert(std::string(permit));audit_head_=digest;}
 void commit_outcome(std::string_view permit,std::string_view canonical,std::string_view digest)override{if(!permits_.contains(std::string(permit)))throw std::runtime_error("outcome_unknown_permit");append_audit(canonical);append("AUDIT\t"+std::string(digest));audit_head_=digest;}
 std::uint64_t service_generation()const override{return generation_;}
 void begin_behavior_session(std::string_view id,std::string_view binding)override{if(behavior_start_.contains(std::string(id)))throw std::runtime_error("behavior_session_replay");append("BEHAVIOR_BEGIN\t"+std::string(id)+"\t"+std::to_string(generation_)+"\t"+std::string(binding));behavior_start_[std::string(id)]={generation_,std::string(binding)};}
 void record_behavior_event(std::string_view id,std::string_view event,std::string_view evidence)override{if(!behavior_start_.contains(std::string(id))||!kp::valid_identifier(event)||!kp::valid_hex64(evidence))throw std::runtime_error("behavior_event_invalid");auto&events=behavior_events_[std::string(id)];if(events.contains(std::string(event))){if(events[std::string(event)]!=evidence)throw std::runtime_error("behavior_event_conflict");return;}append("BEHAVIOR_EVENT\t"+std::string(id)+"\t"+std::string(event)+"\t"+std::string(evidence));events[std::string(event)]=std::string(evidence);}
 kp::json::value behavior_session(std::string_view id)const override{auto it=behavior_start_.find(std::string(id));if(it==behavior_start_.end())throw std::runtime_error("behavior_session_missing");kp::json::value::array rows;auto events=behavior_events_.find(std::string(id));if(events!=behavior_events_.end())for(const auto&[event,digest]:events->second)rows.emplace_back(kp::json::value::object{{"event",kp::json::value(event)},{"evidenceSha256",kp::json::value(digest)}});return kp::json::value(kp::json::value::object{{"behaviorSessionId",kp::json::value(std::string(id))},{"startGeneration",kp::json::value(static_cast<std::int64_t>(it->second.first))},{"currentGeneration",kp::json::value(static_cast<std::int64_t>(generation_))},{"exactRunBindingSha256",kp::json::value(it->second.second)},{"events",kp::json::value(rows)}});}
 private:std::filesystem::path state_,audit_,rev_,approvals_;win_handle file_;std::unordered_set<std::string>nonces_,permits_;std::unordered_map<std::string,std::uint64_t>uses_;std::unordered_map<std::string,std::string>persisted_approvals_;mutable std::uint64_t epoch_=0;mutable std::unordered_set<std::string>revoked_;std::string audit_head_=std::string(64,'0');std::uint64_t generation_=0;std::unordered_map<std::string,std::pair<std::uint64_t,std::string>>behavior_start_;std::unordered_map<std::string,std::map<std::string,std::string>>behavior_events_;
 void load(){SetFilePointer(file_.h,0,nullptr,FILE_BEGIN);std::string all;std::array<char,4096>b{};DWORD n=0;while(ReadFile(file_.h,b.data(),checked_dword(b.size(),"state_read_buffer_too_large"),&n,nullptr)&&n)all.append(b.data(),n);std::istringstream in(all);std::string line;while(std::getline(in,line)){std::vector<std::string>f;std::size_t p=0;while(true){auto q=line.find('\t',p);f.push_back(line.substr(p,q==std::string::npos?q:q-p));if(q==std::string::npos)break;p=q+1;}if(f.size()==4&&f[0]=="USE"){uses_[f[1]]=std::stoull(f[2]);nonces_.insert(f[3]);}else if(f.size()==2&&f[0]=="PERMIT")permits_.insert(f[1]);else if(f.size()==2&&f[0]=="AUDIT")audit_head_=f[1];else if(f.size()==3&&f[0]=="APPROVAL")persisted_approvals_[f[1]]=f[2];else if(f.size()==2&&f[0]=="GENERATION")generation_=std::max<std::uint64_t>(generation_,std::stoull(f[1]));else if(f.size()==4&&f[0]=="BEHAVIOR_BEGIN"&&kp::valid_hex64(f[3]))behavior_start_[f[1]]={std::stoull(f[2]),f[3]};else if(f.size()==4&&f[0]=="BEHAVIOR_EVENT"&&kp::valid_hex64(f[3]))behavior_events_[f[1]][f[2]]=f[3];}}
 void load_rev()const{auto v=kp::json::parse(kp::read_text_file(rev_));const auto&o=v.as_object();epoch_=static_cast<std::uint64_t>(kp::json::required_int(o,"revocationEpoch"));revoked_.clear();for(const auto&x:kp::json::required_array(o,"revokedCapabilities"))if(x.is_string())revoked_.insert(x.as_string());}
 void append(const std::string&line){SetFilePointer(file_.h,0,nullptr,FILE_END);auto row=line+"\n";DWORD n=0;if(!WriteFile(file_.h,row.data(),checked_dword(row.size(),"state_row_too_large"),&n,nullptr)||static_cast<std::size_t>(n)!=row.size()||!FlushFileBuffers(file_.h))throw std::runtime_error("state_persist_failed");}
 void append_audit(std::string_view line){win_handle f(CreateFileW(audit_.c_str(),FILE_APPEND_DATA,FILE_SHARE_READ,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_HIDDEN,nullptr));if(f.h==INVALID_HANDLE_VALUE)throw std::runtime_error("audit_open_failed");std::string row(line);row.push_back('\n');DWORD n=0;if(!WriteFile(f.h,row.data(),checked_dword(row.size(),"state_row_too_large"),&n,nullptr)||static_cast<std::size_t>(n)!=row.size()||!FlushFileBuffers(f.h))throw std::runtime_error("audit_persist_failed");}};

std::string read_frame(HANDLE pipe,std::size_t limit){std::array<unsigned char,4>h{};DWORD n=0;if(!ReadFile(pipe,h.data(),checked_dword(h.size(),"frame_header_too_large"),&n,nullptr)||static_cast<std::size_t>(n)!=h.size())throw std::runtime_error("frame_header_failed");DWORD size=(DWORD(h[0])<<24)|(DWORD(h[1])<<16)|(DWORD(h[2])<<8)|h[3];if(size==0||size>limit)throw std::runtime_error("frame_size_invalid");std::string body(size,'\0');DWORD total=0;while(total<size){if(!ReadFile(pipe,body.data()+total,size-total,&n,nullptr)||n==0)throw std::runtime_error("frame_body_failed");total+=n;}return body;}
void write_frame(HANDLE pipe,std::string_view body){if(body.size()>static_cast<std::size_t>((std::numeric_limits<DWORD>::max)()))throw std::runtime_error("frame_body_too_large");std::array<unsigned char,4>h{static_cast<unsigned char>(body.size()>>24),static_cast<unsigned char>(body.size()>>16),static_cast<unsigned char>(body.size()>>8),static_cast<unsigned char>(body.size())};DWORD n=0;if(!WriteFile(pipe,h.data(),checked_dword(h.size(),"frame_header_too_large"),&n,nullptr)||static_cast<std::size_t>(n)!=h.size())throw std::runtime_error("frame_write_header_failed");std::size_t off=0;while(off<body.size()){DWORD chunk=0;if(!WriteFile(pipe,body.data()+off,checked_dword(body.size()-off,"frame_chunk_too_large"),&chunk,nullptr)||chunk==0)throw std::runtime_error("frame_write_body_failed");off+=chunk;}FlushFileBuffers(pipe);}
kp::peer_identity authenticate(HANDLE pipe,const config&c){ULONG pid=0;if(!GetNamedPipeClientProcessId(pipe,&pid)||pid==0)throw std::runtime_error("pipe_client_pid_unavailable");win_handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid));if(!process.h)throw std::runtime_error("pipe_client_process_open_failed");win_handle token;token.h=nullptr;if(!OpenProcessToken(process.h,TOKEN_QUERY,&token.h))throw std::runtime_error("pipe_client_token_failed");auto sid=token_sid(token.h);auto image=process_image(pid);auto hash=file_sha256(image);DWORD session=0;if(!ProcessIdToSessionId(pid,&session))throw std::runtime_error("pipe_client_session_unavailable");const bool worker=sid==c.worker_sid||token_is_appcontainer(token.h);if(worker)return{"windows",narrow(sid),hash,narrow(image),std::to_string(session),pid,false,true};if(sid!=c.desktop_sid)throw std::runtime_error("desktop_sid_mismatch");if(hash!=c.desktop_hash)throw std::runtime_error("desktop_image_digest_mismatch");if(!verify_authenticode(image))throw std::runtime_error("desktop_authenticode_invalid");if(signer_certificate_sha256(image)!=c.desktop_publisher_sha256)throw std::runtime_error("desktop_publisher_identity_mismatch");return{"windows",narrow(sid),hash,narrow(image),std::to_string(session),pid,true,false};}
PSECURITY_DESCRIPTOR pipe_sd(const config&c){std::wstring sddl=L"D:P(A;;GA;;;SY)(A;;GRGW;;;"+c.desktop_sid+L")(A;;GRGW;;;"+c.worker_sid+L")";PSECURITY_DESCRIPTOR sd=nullptr;if(!ConvertStringSecurityDescriptorToSecurityDescriptorW(sddl.c_str(),SDDL_REVISION_1,&sd,nullptr))throw std::runtime_error("pipe_sddl_invalid");return sd;}
void serve(const config&c){auto core_cfg=kp::load_authority_config(c.policy);win_crypto crypto(c);win_state state(c.state,c.audit,c.revocations,c.approvals);kp::authority_core core(std::move(core_cfg),crypto,state);std::unique_ptr<void,decltype(&LocalFree)>sd(pipe_sd(c),LocalFree);SECURITY_ATTRIBUTES sa{static_cast<DWORD>(sizeof(SECURITY_ATTRIBUTES)),sd.get(),FALSE};while(WaitForSingleObject(g_stop_event,0)!=WAIT_OBJECT_0){win_handle pipe(CreateNamedPipeW(c.pipe.c_str(),PIPE_ACCESS_DUPLEX|FILE_FLAG_FIRST_PIPE_INSTANCE,PIPE_TYPE_BYTE|PIPE_READMODE_BYTE|PIPE_WAIT|PIPE_REJECT_REMOTE_CLIENTS,16,1024*1024,1024*1024,5000,&sa));if(pipe.h==INVALID_HANDLE_VALUE)throw std::runtime_error("named_pipe_create_failed");BOOL connected=ConnectNamedPipe(pipe.h,nullptr)?TRUE:(GetLastError()==ERROR_PIPE_CONNECTED);if(!connected)continue;try{auto peer=authenticate(pipe.h,c);auto req=kp::json::parse(read_frame(pipe.h,static_cast<std::size_t>(core_cfg.max_request_bytes)));if(peer.worker_principal){core.note_worker_denial(kp::json::required_string(req.as_object(),"behaviorSessionId"),peer,kp::json::required_string(req.as_object(),"workerIdentitySha256"));throw std::runtime_error("worker_principal_denied");}write_frame(pipe.h,kp::json::canonical(core.handle(req,peer)));}catch(const std::exception&e){write_frame(pipe.h,kp::json::canonical(kp::denied_response(e.what())));}DisconnectNamedPipe(pipe.h);}}
void set_status(DWORD state,DWORD error=NO_ERROR){g_status.dwServiceType=SERVICE_WIN32_OWN_PROCESS;g_status.dwCurrentState=state;g_status.dwControlsAccepted=state==SERVICE_RUNNING?SERVICE_ACCEPT_STOP|SERVICE_ACCEPT_SHUTDOWN:0;g_status.dwWin32ExitCode=error;g_status.dwWaitHint=30000;SetServiceStatus(g_status_handle,&g_status);}
void WINAPI control(DWORD code){if(code==SERVICE_CONTROL_STOP||code==SERVICE_CONTROL_SHUTDOWN){set_status(SERVICE_STOP_PENDING);SetEvent(g_stop_event);}}
std::filesystem::path service_config_path(){if(!g_service_config.empty())return g_service_config;wchar_t buffer[32768]{};DWORD n=GetEnvironmentVariableW(L"KRISTIN_P1A_CONFIG",buffer,32768);if(!n||n>=32768)throw std::runtime_error("service_config_required");return std::filesystem::path(std::wstring(buffer,n));}
void WINAPI service_main(DWORD,wchar_t**){g_status_handle=RegisterServiceCtrlHandlerW(L"KristinP1Authority",control);if(!g_status_handle)return;g_stop_event=CreateEventW(nullptr,TRUE,FALSE,nullptr);set_status(SERVICE_START_PENDING);try{auto path=service_config_path();auto c=load_config(path);set_status(SERVICE_RUNNING);serve(c);set_status(SERVICE_STOPPED);}catch(...){set_status(SERVICE_STOPPED,ERROR_SERVICE_SPECIFIC_ERROR);}if(g_stop_event)CloseHandle(g_stop_event);}
int provision_key(const std::wstring&name){ncrypt_handle provider,key;if(NCryptOpenStorageProvider(&provider.h,MS_PLATFORM_CRYPTO_PROVIDER,0)!=ERROR_SUCCESS)throw std::runtime_error("platform_ksp_required");DWORD create_flags=NCRYPT_MACHINE_KEY_FLAG;
#ifdef NCRYPT_REQUIRE_VBS_FLAG
create_flags|=NCRYPT_REQUIRE_VBS_FLAG;
#endif
auto st=NCryptCreatePersistedKey(provider.h,&key.h,BCRYPT_ECDSA_P256_ALGORITHM,name.c_str(),0,create_flags);if(st==NTE_EXISTS)return 0;if(st!=ERROR_SUCCESS)throw std::runtime_error("cng_key_create_failed");DWORD export_policy=0;if(NCryptSetProperty(key.h,NCRYPT_EXPORT_POLICY_PROPERTY,reinterpret_cast<PBYTE>(&export_policy),static_cast<DWORD>(sizeof(export_policy)),NCRYPT_PERSIST_FLAG)!=ERROR_SUCCESS)throw std::runtime_error("cng_export_policy_set_failed");DWORD usage=NCRYPT_ALLOW_SIGNING_FLAG;if(NCryptSetProperty(key.h,NCRYPT_KEY_USAGE_PROPERTY,reinterpret_cast<PBYTE>(&usage),static_cast<DWORD>(sizeof(usage)),NCRYPT_PERSIST_FLAG)!=ERROR_SUCCESS||NCryptFinalizeKey(key.h,NCRYPT_PERSIST_FLAG)!=ERROR_SUCCESS)throw std::runtime_error("cng_key_finalize_failed");return 0;}
} // namespace

int wmain(int argc,wchar_t**argv)try{if(argc==2&&std::wstring(argv[1])==L"--source-self-test"){std::cout<<"{\"status\":\"passed\",\"platform\":\"windows\",\"authorityCore\":\"v2\",\"completionEligible\":false}\n";return 0;}if(argc>=2&&std::wstring(argv[1])==L"--provision-key"){if(argc!=3)throw std::runtime_error("key_name_required");return provision_key(argv[2]);}if(argc>=2&&std::wstring(argv[1])==L"--store-lsa-secret-stdin"){if(argc!=3)throw std::runtime_error("secret_name_required");auto secret=read_secret_hex_stdin();try{lsa_store(argv[2],secret);}catch(...){SecureZeroMemory(secret.data(),secret.size()*sizeof(wchar_t));throw;}SecureZeroMemory(secret.data(),secret.size()*sizeof(wchar_t));return 0;}if(argc>=2&&std::wstring(argv[1])==L"--console"){if(argc!=3)throw std::runtime_error("config_path_required");g_stop_event=CreateEventW(nullptr,TRUE,FALSE,nullptr);auto c=load_config(argv[2]);serve(c);return 0;}if(argc>=2&&std::wstring(argv[1])==L"--service-config"){if(argc!=3)throw std::runtime_error("config_path_required");g_service_config=argv[2];}SERVICE_TABLE_ENTRYW table[]={{const_cast<LPWSTR>(L"KristinP1Authority"),service_main},{nullptr,nullptr}};if(!StartServiceCtrlDispatcherW(table))throw std::runtime_error("service_dispatcher_failed");return 0;}catch(const std::exception&e){std::cerr<<"P1A Windows authority fatal: "<<e.what()<<"\n";return 1;}
