#!/usr/bin/env python3
"""Lightweight lexical sanity checks for Dart files generated by the bundle.

This is NOT a Dart parser and never claims analyzer/test success. It catches
packaging mistakes that are still useful to detect offline: unbalanced lexical
delimiters, unterminated strings/comments, imports after declarations, and
duplicate top-level class/enum/mixin names in full generated source units.
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def _load(name: str):
    path = ROOT / name
    spec = importlib.util.spec_from_file_location(
        f'_dart_shape_{name.replace(".", "_")}', path
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f'cannot import {name}')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _final_full_units() -> dict[str, str]:
    composition = _load('validate_anchor_composition.py')
    result: dict[str, str] = {}
    operations_by_file = composition._operations_by_file()
    for path, operations in operations_by_file.items():
        if not operations or operations[0][0] != 'set' or not path.endswith('.dart'):
            continue
        content = ''
        for operation in operations:
            if operation[0] == 'set':
                content = operation[3]
            else:
                _, script, function_name, _, _ = operation
                content = getattr(composition.MODULES[script], function_name)(content)
        result[path] = content

    utility = _load('apply_deterministic_utility_time.py')
    result['lib/product/utility_time.dart'] = utility.UTILITY_SOURCE
    return result


def _balanced(source: str) -> tuple[bool, str]:
    stack: list[tuple[str, int]] = []
    pairs = {')': '(', ']': '[', '}': '{'}
    state = 'code'
    quote = ''
    triple = False
    raw = False
    block_depth = 0
    i = 0
    while i < len(source):
        char = source[i]
        nxt = source[i + 1] if i + 1 < len(source) else ''
        if state == 'line_comment':
            if char == '\n':
                state = 'code'
            i += 1
            continue
        if state == 'block_comment':
            if char == '/' and nxt == '*':
                block_depth += 1
                i += 2
                continue
            if char == '*' and nxt == '/':
                block_depth -= 1
                i += 2
                if block_depth == 0:
                    state = 'code'
                continue
            i += 1
            continue
        if state == 'string':
            if triple:
                if source.startswith(quote * 3, i):
                    state = 'code'
                    i += 3
                    continue
                if char == '\\' and not raw:
                    i += 2
                    continue
                i += 1
                continue
            if char == quote:
                state = 'code'
                i += 1
                continue
            if char == '\\' and not raw:
                i += 2
                continue
            i += 1
            continue

        if char == '/' and nxt == '/':
            state = 'line_comment'
            i += 2
            continue
        if char == '/' and nxt == '*':
            state = 'block_comment'
            block_depth = 1
            i += 2
            continue
        if char in "'\"" or (char in 'rR' and nxt in "'\""):
            raw = char in 'rR'
            if raw:
                i += 1
                char = source[i]
            quote = char
            triple = source.startswith(char * 3, i)
            state = 'string'
            i += 3 if triple else 1
            continue
        if char in '([{':
            stack.append((char, i))
        elif char in ')]}':
            if not stack or stack[-1][0] != pairs[char]:
                return False, f'mismatched {char!r} at offset {i}'
            stack.pop()
        i += 1

    if state in {'string', 'block_comment'}:
        return False, f'unterminated {state.replace("_", " ")}'
    if stack:
        return False, f'unclosed delimiter {stack[-1][0]!r} at offset {stack[-1][1]}'
    return True, 'ok'


def _imports_before_declarations(source: str) -> bool:
    seen_declaration = False
    for raw in source.splitlines():
        line = raw.strip()
        if not line or line.startswith('//') or line.startswith('///'):
            continue
        if re.match(r'^(?:abstract\s+|sealed\s+|final\s+|base\s+|interface\s+)?(?:class|enum|mixin)\b', line):
            seen_declaration = True
        if seen_declaration and line.startswith('import '):
            return False
    return True


def main() -> int:
    failures: list[str] = []
    for path, source in sorted(_final_full_units().items()):
        ok, detail = _balanced(source)
        if not ok:
            failures.append(f'{path}: {detail}')
            continue
        if not _imports_before_declarations(source):
            failures.append(f'{path}: import appears after a top-level declaration')
            continue
        declarations = re.findall(
            r'^\s*(?:abstract\s+|sealed\s+|final\s+|base\s+|interface\s+)?'
            r'(?:class|enum|mixin)\s+(\w+)',
            source,
            re.MULTILINE,
        )
        duplicates = sorted({name for name in declarations if declarations.count(name) > 1})
        if duplicates:
            failures.append(f'{path}: duplicate top-level declarations {duplicates}')
            continue
        print(
            f'OK generated Dart shape: {path} '
            f'({len(declarations)} top-level class/enum/mixin declaration(s))'
        )
    if failures:
        for failure in failures:
            print(f'FAIL generated Dart shape: {failure}')
        raise SystemExit(f'{len(failures)} generated Dart lexical sanity failure(s)')
    print('OK generated Dart lexical sanity. NOTE: dart analyze/test still required.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
